### PR TITLE
INT-4133: Merge Java DSL Core functionality

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-4133

Mostly copy/paste and changes according Java 8 and Reactor 3.0 foundations

### CODE REVIEW

**Comment by garyrussell** [comment]
Unrelated, but the travis failure failed for me too...

`testReaperReapsAnEmptyGroupAfterConfiguredDelay` 

Since we have `setMinimumTimeoutForEmptyGroups` the reaper is no longer needed.

**Comment by artembilan** [comment]
Doh... I fixed that in my PR for `Aggregator` and you have merged it yesterday.
This my PR must be rebased to the master.

**Comment by artembilan** [comment]
Do not merge yet, BTW.
I found a couple of non-actual JavaDocs to fix.

**Comment by garyrussell** [comment]
Actually, it failed for me after the rebase

**Comment by garyrussell** [comment]
I am looking at the test and it has a race condition for sure.

**Comment by artembilan** [comment]
> I am looking at the test and it has a race condition for sure.

Let me know what is that and I'll utilize it in the next commit.
Thanks

**Comment by garyrussell** [comment]
```
assertEquals(1, TestUtils.getPropertyValue(handler, "messageStore.groupIdToMessageGroup", Map.class).size());
groupStore.expireMessageGroups(0);
assertEquals(1, TestUtils.getPropertyValue(handler, "messageStore.groupIdToMessageGroup", Map.class).size());
```

The second assert fails because of the internal reap.

**Comment by garyrussell** [comment]
I wonder if we should have used a separate boolean for internal reaping - or maybe we should deprecate the reaper altogether?

**Comment by artembilan** [comment]
I guess `handler.setMinimumTimeoutForEmptyGroups(100);` is not enough.
Well, all these time-based tests are very dangerous and even with long enough delay, we may end up with the race condition, because there is no guaranty how long we have walked aside until we come back to to the next operator in this code block.

**Comment by garyrussell** [comment]
No - it worked fine before - the problem now is the  group is now removed internally.

**Comment by artembilan** [comment]
There is no internal reaper:
```
handler.handleMessage(message);
handler.setMinimumTimeoutForEmptyGroups(100);
```
I mock it a bit. First send a message to complete the group and only after that let the reaper to do its work based on the new timeout :smile:

**Comment by artembilan** [comment]
There is really race condition that the group can be reaped exactly on the first `groupStore.expireMessageGroups(0);`, just because `handler.setMinimumTimeoutForEmptyGroups(100);` is too small. 
My idea was to minimize the test time as much as possible, but try to keep its logic, that we don't reap the group for the first attempt because not a time yet.

**Comment by garyrussell** [comment]
Ah - got it - missed that; I thought this was an existing test that was broken by the auto-reap.

**Comment by garyrussell** [comment]
Ah - got it - missed that; I see you reduced the timeout.

**Comment by artembilan** [comment]
Right, that was a problem after first new feature cycle, but then I changed the test to simulate reaper functionality.
Now I see that the time is small.

Well, I'll reinstate it for now, but we should bear in mind that it might fail again in the future because of time window between sentences execution.

**Comment by garyrussell** [comment]
I see no javadocs in that commit 😄 but I see it has the same headline as the previous one

**Comment by artembilan** [comment]
M-m-m. Missed to `amend commit`.
Is that so critical?

**Comment by garyrussell** [comment]
No; just kidding - BTW, can't we simply reduce the property?

Set to 10_000 show that it doesn't expire; then reduce to 100 ?

**Comment by garyrussell** [comment]
Yep - works nicely.

**Comment by artembilan** [comment]
To be clear there are some breaking changes in the current DSL state.
There are no any more Factories and Functions for Adapters, MessageSources and Gateways. 
Just because we can't keep that code in the `Core`.
Some `Transformers` methods have been removed as well. I think the best place for them is target module, e.g. `Files.toString()/toByteArray()`. WDYT?

The `.delay()` EIP-methods have been changed as well, because of clash between Java 8 `Consumer` and `Function`.
Similar problem is with `RecipientListRouterSpec`, where there is an ambiguity between `MessageSelector` and `GenericSelector`. Although the target test is OK. So, `MessageSelector` variant has been renamed to the `recipientMessageSelector` to avoid clash during code completion, at least.

There are a couple TODO, which I would like to utilize in the core code directly. But that is a different story.

The Reactor stuff I'm going to address in the existing PR. Need to figure out a new `Flux` style for testing. Plus I guess that Reactive Streams support in DSL can be based on the `ReactiveChannel` and `ReactiveEndpoint`. So, that is a story for that PR as well.

Will fix Aggregator test as you described.
Thanks

**Comment by garyrussell** [comment]
Merged as bde1efa9ee16fabe813bbc6c01ba583acb1154b5

**Pull request closed without merging**
