### PR TITLE
INT-4206: Upgrade to Mockito 2.5

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-4206

* Fix unnecessary dependency resolution in BOM module
* Fix `MessagingMethodInvokerHelper` to handle `$MockitoMock$` generated classed which isn't CGLib `Proxies` any more
* Provide fixes for test classes according upgrade to Mockito `2.5`
* Fix Ceckstyle do not allow static imports for deprecated Mockito classes

### CODE REVIEW

**Comment by artembilan** [comment]
With IO Platform we have such a problem:
```
gradlew clean :spring-integration-event:springIoCheck -PplatformVersion=Cairo-BUILD-SNAPSHOT -PJDK8_HOME=d:/Java/jdk8
...
:spring-integration-event:springIoJdk8Test

org.springframework.integration.event.config.EventInboundChannelAdapterParserTests > initializationError FAILED
    java.lang.IllegalStateException

org.springframework.integration.event.config.EventOutboundChannelAdapterParserTests > initializationError FAILED
    java.lang.IllegalStateException

org.springframework.integration.event.inbound.ApplicationEventListeningMessageProducerTests > applicationContextEvents FAILED
    org.springframework.beans.factory.BeanDefinitionStoreException at ApplicationEventListeningMessageProducerTests.java:120
        Caused by: java.io.FileNotFoundException at ApplicationEventListeningMessageProducerTests.java:120

16 tests completed, 3 failed
:spring-integration-event:springIoJdk8Test FAILED
```
Like it resolves SF to some wrong version. But at the same time we have this dependency tree:
```
gradlew clean :spring-integration-event:dependencies --configuration springIoTestRuntime -PplatformVersion=Cairo-BUILD-SNAPSHOT
...
Project :spring-integration-event - Spring Integration ApplicationEvent Support
------------------------------------------------------------

springIoTestRuntime - Runtime dependencies for source set 'spring io test'.
+--- project :spring-integration-core
|    +--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT
|    |    \--- commons-logging:commons-logging:1.2
|    +--- org.springframework:spring-aop:5.0.0.BUILD-SNAPSHOT
|    |    +--- org.springframework:spring-beans:5.0.0.BUILD-SNAPSHOT
|    |    |    \--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT (*)
|    |    \--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT (*)
|    +--- org.springframework:spring-context:5.0.0.BUILD-SNAPSHOT
|    |    +--- org.springframework:spring-aop:5.0.0.BUILD-SNAPSHOT (*)
|    |    +--- org.springframework:spring-beans:5.0.0.BUILD-SNAPSHOT (*)
|    |    +--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT (*)
|    |    \--- org.springframework:spring-expression:5.0.0.BUILD-SNAPSHOT
|    |         \--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT (*)
|    +--- org.springframework:spring-messaging:5.0.0.BUILD-SNAPSHOT
|    |    +--- org.springframework:spring-beans:5.0.0.BUILD-SNAPSHOT (*)
|    |    +--- org.springframework:spring-context:5.0.0.BUILD-SNAPSHOT (*)
|    |    \--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT (*)
|    +--- org.springframework:spring-tx:5.0.0.BUILD-SNAPSHOT
|    |    +--- org.springframework:spring-beans:5.0.0.BUILD-SNAPSHOT (*)
|    |    \--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT (*)
|    +--- org.springframework.retry:spring-retry:1.2.0.RC1
|    +--- io.projectreactor:reactor-core:3.0.4.RELEASE
|    |    \--- org.reactivestreams:reactive-streams:1.0.0
|    +--- com.fasterxml.jackson.core:jackson-databind:2.7.3 -> 2.8.5
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.8.0 -> 2.8.5
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.8.5
|    +--- com.jayway.jsonpath:json-path:2.2.0
|    |    \--- net.minidev:json-smart:2.2.1
|    |         \--- net.minidev:accessors-smart:1.1
|    |              \--- org.ow2.asm:asm:5.0.3
|    +--- io.fastjson:boon:0.33
|    +--- com.esotericsoftware:kryo-shaded:3.0.3
|    |    +--- com.esotericsoftware:minlog:1.3.0
|    |    \--- org.objenesis:objenesis:2.1 -> 2.4
|    \--- io.projectreactor.addons:reactor-test:3.0.4.RELEASE
|         \--- io.projectreactor:reactor-core:3.0.4.RELEASE (*)
+--- project :spring-integration-test
|    +--- junit:junit:4.12
|    +--- org.hamcrest:hamcrest-all:1.3
|    +--- org.mockito:mockito-core:2.5.4
|    |    +--- net.bytebuddy:byte-buddy:1.6.0
|    |    +--- net.bytebuddy:byte-buddy-agent:1.6.0
|    |    \--- org.objenesis:objenesis:2.4
|    +--- org.springframework:spring-context:5.0.0.BUILD-SNAPSHOT (*)
|    +--- org.springframework:spring-messaging:5.0.0.BUILD-SNAPSHOT (*)
|    +--- org.springframework:spring-test:5.0.0.BUILD-SNAPSHOT
|    |    \--- org.springframework:spring-core:5.0.0.BUILD-SNAPSHOT (*)
|    \--- log4j:log4j:1.2.17
\--- org.slf4j:slf4j-log4j12:1.7.21 -> 1.7.22
     +--- org.slf4j:slf4j-api:1.7.22
     \--- log4j:log4j:1.2.17
```

So, everything looks correct, unless a lot of test fail with similar "File not found" problem.

I tried just with `gradlew clean test --refresh-dependencies` - works well 😢 

/CC @wilkinsona

**Comment by wilkinsona** [comment]
We've seen similar problems caused by a corrupted Spring Framework snapshot jar where refreshing dependencies has fixed it. This looks like it could be the same thing

**Comment by garyrussell** [comment]
@wilkinsona It looks like the problem is because SI puts its test XMLs in src/test/java, not src/test/resources.

I just ran a test with 

    $ ./gradlew :spring-integration-stream:springIoCheck --continue --no-daemon -PplatformVersion=Cairo-BUILD-SNAPSHOT -PJDK8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/

and it fails; moving the XMLs under resources solves it.

I realize this is not standard from a maven perspective but SI has always done it (well before I joined the project).

BTW, now we're java 8, can't we get rid of the second run now - just run the JDK8 compatibility tests?

**Comment by wilkinsona** [comment]
I saw that in Spring Social too. Which version of the IO plugin are you using? I thought I'd fixed in in 0.0.6.RELEASE thanks to [this commit](https://github.com/spring-gradle-plugins/spring-io-plugin/commit/8239020eb2a94d39acf3d280d21976fcd9df0bb6).

**Comment by garyrussell** [comment]
0.0.6.RELEASE - https://github.com/spring-projects/spring-integration/pull/2026/files#diff-c197962302397baf3a4cc36463dce5ea

**Comment by artembilan** [comment]
@wilkinsona ,
thank you for reaching us!

But look what you have there:
```
springIoTestSourceSet.getJava().setSrcDirs(testSourceSet.getJava().getSrcDirs());
springIoTestSourceSet.getResources().setSrcDirs(testSourceSet.getResources().getSrcDirs());
```
but according to our requirements it looks like you should copy the `testSourceSet.getJava().getSrcDirs()` to the `springIoTestSourceSet.getResources()` as well.

Or... that is correct but with wrong order. 
I mean that our 
```
sourceSets {
	test {
		resources {
			srcDirs = ['src/test/resources', 'src/test/java']
		}
	}
}
```
is evaluated a bit later than logic in the IO plugin...
I think we can move this discussion somewhere outside of the PR.
See my email on the matter or let's continue in the Slack !

**Comment by artembilan** [comment]
For back tracking : https://github.com/spring-projects/spring-integration/commit/bc525cf6ea194034a35f2f9df310266f0583ce6a

**Pull request merged**
