### PR TITLE
Custom Session dirty logic

### PR DESCRIPTION
**Pull request by alturkovic**
Allows any session to implement its dirty logic.

https://github.com/spring-projects/spring-integration/issues/2687

### CODE REVIEW

**Review by artembilan — APPROVED** [review]
Nice!

@garyrussell ?

**Comment by garyrussell** [comment]
Thanks @alturkovic 

LGTM; cherry-pick to 5.0.x?

**Comment by artembilan** [comment]
... and cherry-picked to `5.0.x`

@alturkovic ,

Thank you very much for the contribution.
Looking forward for more!

**Comment by garyrussell** [comment]
@alturkovic If you have further suggestions as to how to make the CSF easier to support other pool implementations, rather than having to implement a completely new one, feel free to discuss.

**Comment by alturkovic** [comment]
@garyrussell  Would you prefer to continue this discussion here or in a new Issue? I have some thoughts about CSF...

**Comment by garyrussell** [comment]
@alturkovic Yes, please, a new issue would be good.

**Pull request merged**
