### PR TITLE
[REVIEW] INT-3562: Configurable SpEL Parser

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-3562

Just looking for feedback for the approach before I do more work.

I don't think the bean name pattern in the JIRA is such a good idea.

This tecnique doesn't support using different parsers for different expressions in the same bean but I don't think that's critical at this point.

### CODE REVIEW

**Comment by artembilan** [comment]
I wasn't sure in the goal of this JIRA from the beginning and looking at this change I'm convinced one more time. See `SpelCompilerMode` JavaDocs:
```
    /**
	 * In mixed mode, expression evaluation silently switches between interpreted and compiled over time.
	 * After a number of runs the expression gets compiled. If it later fails (possibly due to inferred
	 * type information changing) then that will be caught internally and the system switches back to
	 * interpreted mode. It may subsequently compile it again later.
	 */
	MIXED
```
So, if someone is facing an issue with its expression in the `IMMEDIATE` mode, he can switch to the `MIXED` safely for the whole app, or just live in that mode forever!

**Comment by garyrussell** [comment]
I generally agree; my thought is someone might have just one expression that will always fail in mixed mode and hence will cost more than explicitly using OFF for that expression.

But, as you can see, it is a lot of work. So I am ok with putting this on the general backlog and perhaps handle it if a real user has a problem.

**Comment by artembilan** [comment]
Makes sense. Push as low-level task to the far future :smile: 
The new `RemoteFileTemplate` issue is more interesting - https://jira.spring.io/browse/INT-3773

**Comment by garyrussell** [comment]
Closed; deferred.

**Pull request closed without merging**
