### PR TITLE
INT-3723: Fix HTTP module according SF changes

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-3723

Since `RequestMappingHandlerMapping` has came back to the `@RequestMapping` parsing,
just restore the previous logic with `@RequestMapping` generation in the `IntegrationRequestMappingHandlerMapping`

### CODE REVIEW

**Comment by artembilan** [comment]
@sbrannen, pay attention, please, to this Spring Integration changes which we were forced to do according to your last `Synthesizing Annotation`. To be honest I really was going to do that with your new logic in the `AnnotationUtils`, but I find this `new RequestMapping` on the fly as more clear and quick style to go.
From other side your `MapAnnotationAttributeExtractor` requires all annotation attributes, even if our `@RequestMapping` has aliases on its attributes. I mean that I expect do not copy/paste the same attribute in my original map if they are connected through the `@AliasFor`. 
Or have I missed anything?

Thank you!

**Comment by sbrannen** [comment]
Hi @artembilan,

First and foremost, thanks so much for paying attention to the new "synthesized annotation" support coming in Spring Framework 4.2. It's very helpful to get early feedback!

I would recommend against instantiating an annotation as an anonymous inner class simply because you never know how the annotation _instance_ will be used by the caller. The reason this is dangerous is that this technique results in an object that implements the annotation's interface incorrectly. For example, `equals()`, `hashCode()`, and `toString()` are broken in terms of the contract for an annotation as defined by the the JLS. Furthermore, even if you do go that route, `annotationType()` must return `Class<org.springframework.web.bind.annotation.RequestMapping>` (i.e., the concrete annotation type).

For the time being, I would recommend the following implementation in order to ensure proper implementation of the annotation according to the specs:

	/**
	 * Create {@link RequestMappingInfo} from a
	 * 'Spring Integration HTTP Inbound Endpoint' {@link RequestMapping}.
	 * @see RequestMappingHandlerMapping#getMappingForMethod
	 */
	private RequestMappingInfo getMappingForEndpoint(HttpRequestHandlingEndpointSupport endpoint) {
		final RequestMapping requestMapping = endpoint.getRequestMapping();

		if (ObjectUtils.isEmpty(requestMapping.getPathPatterns())) {
			return null;
		}

		Map<String, Object> requestMappingAttributes = new HashMap<String, Object>();
		requestMappingAttributes.put("name", endpoint.getComponentName());
		requestMappingAttributes.put("path", requestMapping.getPathPatterns());
		requestMappingAttributes.put("value", requestMapping.getPathPatterns());
		requestMappingAttributes.put("method", requestMapping.getRequestMethods());
		requestMappingAttributes.put("params", requestMapping.getParams());
		requestMappingAttributes.put("headers", requestMapping.getHeaders());
		requestMappingAttributes.put("consumes", requestMapping.getConsumes());
		requestMappingAttributes.put("produces", requestMapping.getProduces());

		org.springframework.web.bind.annotation.RequestMapping annotation =
			AnnotationUtils.synthesizeAnnotation(requestMappingAttributes,
			org.springframework.web.bind.annotation.RequestMapping.class, null);

		return createRequestMappingInfo(annotation, getCustomTypeCondition(endpoint.getClass()));
	}

Yes, I realize it's cumbersome to have to specify the `value` _and_ `path` attributes, but I'll address that in a follow-up comment. ;)

**Comment by sbrannen** [comment]
> From other side your `MapAnnotationAttributeExtractor` requires all annotation attributes, even if our 
`@RequestMapping` has aliases on its attributes. I mean that I expect do not copy/paste the same attribute in my original map if they are connected through the `@AliasFor`.
Or have I missed anything?

No, you have not missed anything. In fact, that's a very valid point!

The validation that `MapAnnotationAttributeExtractor` currently performs was implemented in order to support Spring's internal use case of synthesizing an annotation from merged `AnnotationAttributes` (as created by `AnnotatedElementUtils`), and for that use case it is in fact an error if any attributes defined by the annotation are not present (including aliased attributes).

But... now that you mention it, I can see that there are use cases that would benefit from only having to supply the _bare minimum_ of attributes to synthesize an annotation. In such uses cases, if an attribute is missing it should be set either to value of its alias (if an alias value exists) or to the value of the attribute's _default_ value (if defined), and otherwise an exception should be thrown.

I'll create a JIRA issue to make sure we improve the support for synthesizing annotations from maps as outlined above.

Cheers,

Sam

**Comment by artembilan** [comment]
@sbrannen , thank you very much for such a valuable feedback!

I've just pushed the `AnnotationUtils.synthesizeAnnotation` solution. Of course it works well and there is nothing to complain about with your comments. 
Especial thanks for the point to the JLS :smile: 

Re. `@AliasFor`: we can wait for your JIRA and utilize it in this PR and merge it only after the robust solution from both our sides.

**Comment by sbrannen** [comment]
I just created [SPR-13087](https://jira.spring.io/browse/SPR-13087). So feel free to _watch_ it.

**Comment by sbrannen** [comment]
> Re. `@AliasFor`: we can wait for your JIRA and utilize it in this PR and merge it only after the robust solution from both our sides.

OK!

**Comment by garyrussell** [comment]
> we can wait for your JIRA and utilize it in this PR and merge it only after the robust 

@artembilan , we should either merge this now or disable the nightly that's failing; you know how I dislike red nightlies :smile:

**Comment by sbrannen** [comment]
I'd suggest you go ahead and merge it now.

The only difference between now and after that JIRA issue is that you'll end up with one less line of code. ;)

**Comment by garyrussell** [comment]
Merged as 0fdc63007a2c0931b0a79a074440b47108245020

**Comment by garyrussell** [comment]
Thanks @sbrannen

**Pull request closed without merging**
