### PR TITLE
Adding initial delay option for pollers in XML configuration.

### PR DESCRIPTION
**Pull request by cigaly**
PeriodicTrigger is supporting 'initialDelay' property. However, there is not possible to set that property with XML configuration. Changes are minimal.

### CODE REVIEW

**Comment by garyrussell** [comment]
Thanks for the contribution but, before we can look at your code, we need to be sure you have "signed" the CLA - please see the [contribution guidelines](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md). In particular, changes such as these need a [JIRA issue](https://jira.spring.io/browse/INT) for tracking purposes. Also, some things to bear in mind...

1. The `initial-delay` attribute should be applied for both `fixed-rate` and `fixed-delay` triggers.
2. We require parser tests for changes of this kind - one or more of the existing tests can be enhanced (I haven't looked at your code (and can't without a CLA) but the email notification showing the changed files did not include any tests.

Thanks again; please follow the guidelines and we will look forward to your continuing contributions.

**Comment by garyrussell** [comment]
Please advise if you are prepared to "sign" the CLA - if not, we will have to close the pull request. If you want us to consider implementing this feature, please open a JIRA issue.

**Comment by cigaly** [comment]
Sorry ... I do have very bad understanding of legal language and I am not ready to be sorry later because of some small print so it will be better to close this request.
Sorry for any inconvenience, I was totally unaware of all this procedure :-(

**Comment by garyrussell** [comment]
No problem (but it's really not an onerous requirement, and is typical for open source projects); feel free to open a JIRA 'new feature' issue if you want us to consider this feature.

**Pull request closed without merging**
