### PR TITLE
INT-3693: Eliminate xml-apis Redirect on Build

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-3693

Force xml-apis dep to 1.4.01.

Also add task `listAllDependencies`.

**see: https://discuss.gradle.org/t/oddity-in-the-output-of-dependencyinsight-task/7553/11**

### CODE REVIEW

**Comment by artembilan** [comment]
Gary, what this fix should do?
According to the JIRA it must fix 
> xml-apis#xml-apis;2.0.2 relocated to xml-apis#xml-apis;1.0.b2.
But I see this in the Travis logs:

```
POM relocation to an other version number is not fully supported in Gradle : xml-apis#xml-apis;2.0.2 relocated to xml-apis#xml-apis;1.0.b2.
Please update your dependency to directly use the correct version 'xml-apis#xml-apis;1.0.b2'.
Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
Download https://repo.spring.io/plugins-release/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
Download https://repo.spring.io/plugins-release/org/springframework/build/gradle/spring-io-plugin/0.0.3.RELEASE/spring-io-plugin-0.0.3.RELEASE.jar
```

Have I missed anything ?

**Comment by garyrussell** [comment]
Yikes! When I run `./gradlew listAllDependencies`, I don't see 2.0.2 any more.

I didn't check that the message actually went away.

**Comment by artembilan** [comment]
`gradlew test --refresh-dependencies`
and voila!

**Comment by artembilan** [comment]
```
\--- xalan:xalan:2.7.0
|    |              \--- xml-apis:xml-apis:2.0.2 -> 1.4.01
```
For `gemfire` and `hibernate` dependencies

**Comment by artembilan** [comment]
Looks like we can do nothing with that. Gradle doesn't support silent relocation resolution...

**Comment by garyrussell** [comment]
Let's close this as won't fix - I've already wasted too much time on this annoyance.

**Comment by artembilan** [comment]
:+1: and looks like SF doesn't care about that as well.
Feel free to close yourself

**Pull request closed without merging**
