### PR TITLE
INT-3655: Remove Reactor `Function` usage

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-3655

In addition change `GatewayProxyFactoryBean` to the logic to ensure that the Reactor is really `optional`

### CODE REVIEW

**Comment by artembilan** [comment]
If there is need to add a Migration Guide note, let me know.
The issue in the end-applications may have place, if someone uses our `FunctionIterator` directly.

**Comment by artembilan** [comment]
Repushed with the fix for the `GatewayProxyFactoryBean`

**Comment by garyrussell** [comment]
LGTM; what's new here: https://github.com/garyrussell/spring-integration/commit/93b7b133e8cb92e678ef06c626a3bfc0370a9e9c

**Comment by garyrussell** [comment]
Merged as 75ff56962af2ca558cb109a70c64456d5cd70ecc

**Pull request closed without merging**
