### PR TITLE
INT-3714: Add HTTP CORS support

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-3714

### CODE REVIEW

**Comment by artembilan** [comment]
Pushed

**Comment by artembilan** [comment]
Pushed AMQP version change to M1 instead of B-S

**Comment by garyrussell** [comment]
LGTM; minor doc polish here: https://github.com/garyrussell/spring-integration/commit/910688aa1a8259c018fb740a171de67f1d72e3c0

**Comment by garyrussell** [comment]
Merged as 580ecddcc04247dc422a2d8f38559d8a6cb8425d

**Pull request closed without merging**
