### PR TITLE
make sure the attribute  is taken into account in @Header annotation

### PR DESCRIPTION
**Pull request by chengchen**
Hello,

This PR is related to the issue #2908 that I have submitted.
It's pretty trivial fix and I have run the whole test suite.

Please take a look, many thanks!

Chengchen

### CODE REVIEW

**Comment by artembilan** [comment]
That's indeed a good catch!

Looks like this is only a place where we deal with `Method.getParameterAnnotations()` directly and that standard Java API returns for raw annotations, not those synthesized by Spring like we have in case of `@Payload` in the `getExpressionForPayload()`.

I think we are good to merge this and back-port to `5.1.x`, but at the same time we need to think about using a new `MergedAnnotations` API in the current `master`.
Separate issue though.

@chengchen ,

Thank you for the contribution!

Would you mind also to add your name to the `@author` list for all the affected classes?

**Comment by artembilan** [comment]
I've just realized that we have the same issue with the `@Payload` on the code:
```
Assert.state("".equals(AnnotationUtils.getValue(currentAnnotation)),
	"@Payload on a parameter for a @Publisher method may not contain an expression");
```

so, when I configure (modify existing code in test, essentially) like this:
```
@Publisher
	public void methodWithVoidReturnAndParameterPayloadAnnotation(@Payload(expression = "foo") String payload) {
	}
```
It doesn't fail on that assertion. Just because the the `@AliasFor` is not resolved here again for the same raw Java API issue.

Would you mind to address that as well?

Thanks

**Comment by chengchen** [comment]
@artembilan Definitely, willing to help!

**Comment by artembilan** [comment]
@chengchen ,

thank you very much for the contribution; looking forward for more!

**Comment by chengchen** [comment]
@artembilan thanks for the high reactivity. I am glad to contribute to high quality well managed projects!

**Pull request merged**
