### PR TITLE
INT-2466: adding the SOAP action to the message headers

### PR DESCRIPTION
**Pull request by mauromol**
Pull request for a fix to INT-2466 as discussed on JIRA: https://jira.spring.io/browse/INT-2466

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by artembilan** [comment]
@mauromol !

Welcome to the Spring Integration Contributors team!

For the first PR everything looks excellent.

Only concern is about the commit message format. You can find the proper sample in the last paragraph of our https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md

**Comment by artembilan** [comment]
Grabbing to take a look locally and for simple polishing before merge, BTW...

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/f99183afca7b585fa99b63e435ee79d9ec36209c

Thank you one more time for the contribution!

Feel free to go ahead with any other JIRA which you'd like to see as fixed!

**Comment by mauromol** [comment]
Hi Artem, thanks for the merge! Sorry about the commit comment, I tried to follow the "Commit Guidelines" outlined in *Pro Git*, as suggested by the CONTRIBUTING document, but I really missed the last paragraph about the request to insert the full JIRA link. On the other hand, that paragraph says "Add a JIRA issue link to your first commit comment of the pull request **on the last line**", but the example actually places it on the second line ;-)

I completely approve your polishing, I've just one question. The last unit test (`testExtractStandardHeadersNonEmptySoapAction()`) was meant to test the behaviour of the method `extractStandardHeadersNonEmptySoapAction()` (as the unit test method name suggests) in case of a non-empty SOAP action, just like the previous two were about the cases in which the SOAP action is null or empty. But in your merge, just for the last unit test, you replaced the call to `extractStandardHeadersNonEmptySoapAction()` with a call to `toHeadersFromRequest()`. Is there a particular reason for this?

**Comment by artembilan** [comment]
I did that change because exactly `toHeadersFromRequest()` is invoked from the adapters. I just wondered how it works from the high-level perspective.

Although there was need to have more higher integration test where we expect to see `WebServiceHeaders.SOAP_ACTION` somewhere downstream after the request processing throughout the `<int-ws:inbound-gateway>`. But that is more complex redundant work here and we can live with your simple tests.

BTW, code style must be addressed in the future, too: https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Code-Style

**Comment by mauromol** [comment]
Thanks for the new link. I tried to follow the quick indications in the CONTRIBUTING file (mainly regarding tabs and line wrapping at 90 characters, for the rest I stayed with the Eclipse built-in conventions), but the latter document is much more detailed. Anyway, as a suggestion, it would VERY useful if you provided an Eclipse formatter settings file for this (and maybe something equivalent for the other IDEs). I don't think you all format your code by hand, do you? :-)

BTW, what an ugly style for Javadoc formatting! eheh :-P

Thanks for your patience.

**Pull request closed without merging**
