### PR TITLE
INT-4330 added support for Supplier-based MessageSource

### PR DESCRIPTION
**Pull request by olegz**
- updated documentation
 - updated test

### CODE REVIEW

**Review by artembilan — APPROVED** [review]
LGTM.

Can we also add this functionality to the `IntegrationFlows`, alongside with the `from(MessageSource<?> messageSource)`?

**Comment by olegz** [comment]
@artembilan I was thinking about that as well and then some more, but need to prototype it first. Do you want to wait or do it as a separate PR?

**Comment by artembilan** [comment]
Works for me either way.
We have next Milestone release plan on September 5, but if you need to have this feature immediately, we can merge it as is and you'll come back to us with the Java DSL solution lately.

Thanks!

**Comment by olegz** [comment]
I'd do it as separate commit, so your final call ;)

**Pull request merged**
