### PR TITLE
INT-3629 Fix Sonar Build

### PR DESCRIPTION
**Pull request by ghillert**
- Upgrade to Gradle `2.3`

### CODE REVIEW

**Comment by artembilan** [comment]
Looks like nothing to complain about!
Thanks, @ghillert !

@garyrussell , do we need it urgently or we can wait for the GA release for Gradle and then update this PR ?

**Comment by garyrussell** [comment]
I think we can wait for the gradle GA; I changed the sonar build to point to my copy of this branch and all is well.

I have a similar commit for Spring AMQP. Will generate a PR when gradle is released.

**Comment by ghillert** [comment]
Updated Gradle to RC4 which fixes the transitive dependency issue. See:

http://forums.gradle.org/gradle/topics/breaking-change-regarding-exclude-group-between-gradle-1-12-and-2-3-rc2

**Comment by artembilan** [comment]
The Gradle **2.3** is here!
So, merging...

**Comment by artembilan** [comment]
Merged https://github.com/spring-projects/spring-integration/commit/8c81cffd27cb1bc8a8b17f19ba459a9ba2d58740

**Pull request closed without merging**
