### PR TITLE
Add support for CacheRequestHandlerAdvice

### PR DESCRIPTION
**Pull request by artembilan**
* Fix `AbstractMessageProcessingTransformer` to react for the
`AbstractIntegrationMessageBuilder` invocation result and don't wrap it
into the `Message`
* Demonstrate functionality in the `CacheRequestHandlerAdviceTests`

### CODE REVIEW

**Comment by artembilan** [comment]
We may reconsider priority for this feature.
There might be some obstacles doing it existing `CacheInterceptor` way: https://stackoverflow.com/questions/55073263/ehcache-throwing-notserializableexception-when-moving-to-spring-boot-2

**Comment by artembilan** [comment]
If this is OK, I'll go ahead with docs.

Thanks

**Comment by garyrussell** [comment]
LGTM

**Comment by artembilan** [comment]
Pushed Docs change.

**Comment by garyrussell** [comment]
```
$ ./gradlew clean testAll --parallel
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :spring-integration-core:javadoc
/Users/grussell/Development/spring-integration/spring-integration-core/src/main/java/org/springframework/integration/dsl/HeaderEnricherSpec.java:691: warning: empty <p> tag
         * <p><ul>
           ^
/Users/grussell/Development/spring-integration/spring-integration-core/src/main/java/org/springframework/integration/dsl/HeaderEnricherSpec.java:712: warning: empty <p> tag
         * <p><ul>
           ^
/Users/grussell/Development/spring-integration/spring-integration-core/src/main/java/org/springframework/integration/handler/advice/CacheRequestHandlerAdvice.java:133: warning: no @param for errorHandler
        public void setErrorHandler(CacheErrorHandler errorHandler) {
                    ^
```

**Comment by artembilan** [comment]
@garyrussell ,

I think this is the last issue which can make it into our M1: I have just upgraded to just released Spring Security M2.

Thanks

**Comment by garyrussell** [comment]
Merged as 735e82e7218900c4bbff8a7c267ff3b6dce88cda with minor doc polishing.

**Pull request closed without merging**
