### PR TITLE
Modifications to channels.doc

### PR DESCRIPTION
**Pull request by manueljordan**
[INT-4003](https://jira.spring.io/browse/INT-4003)
Wrong class reference, must be JdbcChannelMessageStore and not JdbcMessageStore

### CODE REVIEW

**Comment by artembilan** [comment]
Hello, @manueljordan !

Recall me, please, that you have signed the CLA. 
Even for such a simple change the CLA must be present.
Otherwise we'll address the PR on our own not mentioning you :smile: .

So, there are several concerns regarding the PullRequest, GitHub and Git at all, but we can address them eventually in the future your contribution.
Now that would be enough to be familiar with our [Contribution Guideline](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc).
Mainly I mean the commit message format.

Thank you for the contribution, anyway!

**Comment by manueljordan** [comment]
Hello @artembilan

Yes, I have signed the CLA. It have generated a kind of code

Pls, let me know I did something wrong to fix it and have that in mind for the future.

Thanks

**Comment by artembilan** [comment]
1. The commit headline must be no longer than 50 symbols
2. The commit headline should contain the JIRA number
3. A blank line after the commit headeline
4. The commit must have a JIRA link
5. The commit must have a brief description for critical or not obvious changes

Also I've just found the good article of one our former colleague on the matter http://chris.beams.io/posts/git-commit/.

But as I said: we can address them eventually. That might be so much info for you to study from the beginning :smile: .

Since you have confirmed the CLA and fix looks good, I'm going to merge it as is with that appropriate fix for the commit message.

That's all foo now from your side.
You can go ahead with other subjects!

**Comment by manueljordan** [comment]
Thanks...

I am going to read carefully the link shared.
I am checking this link too: https://github.com/spring-projects/spring-integration/pull/1784
It to understand the correct approach.

I did realise the commit must has many details. I thought it should be enough since the pull refers a JIRA link. But I understand...

Sorry by the mistake.. first time....

Best Regards!

**Comment by artembilan** [comment]
No any "Sorry" yet! :wink: 
You're doing well.
As I said it isn't critical now, but right: that will safe our time in the future and helps to have the best historical traceability be from JIRA to PR to commit, change log and back.

When I came in the beginning to Spring Contribution I even didn't know Git!
So, that's always do not be familiar with everything.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/590398f9722db75745fd994cb3f1ad1c6cebf913.

Pay attention to the commit message.

Congratulations for your first commit into Spring Integration! :smile: 

Looking forward for more.

**Comment by manueljordan** [comment]
Thanks by the link...

Yes, I did an analysis about the commit message. I have read the post (Chris's article) too

Happy for my first commit :)

**Pull request closed without merging**
