### PR TITLE
Another small typo

### PR DESCRIPTION
**Pull request by nadavc**

### CODE REVIEW

**Comment by artembilan** [comment]
Hey, excellent!
Thank you one more time!

Do you use special tool find those vulnerabilities?
Let us know how much time do you need to find more similar and work out them in this PR instead of polluting with new and new one. :smile:

**Comment by nadavc** [comment]
No special tool... just a pair of eyes :) I didn't think I would find more than the first one, but I happened to run into this as well! If I find more today I'll add them to this PR.

**Comment by artembilan** [comment]
Merging as is after rebasing...

Thank you very much for the contribution!

**Comment by artembilan** [comment]
Merged after rebase

**Pull request closed without merging**
