### PR TITLE
JMS: Doc: Explain Gateway Correlation Techniques

### PR DESCRIPTION
**Pull request by garyrussell**

### CODE REVIEW

**Comment by garyrussell** [comment]
repushed with a couple of typo fixes

**Comment by artembilan** [comment]
Here is a polishing https://github.com/artembilan/spring-integration/commit/816626d091063c012bf953088e6586b7af729cae.
Point me out, please, where are your fixes to merge it properly.

**Comment by garyrussell** [comment]
2 places `/property is provider/property is provided/`.

**Comment by garyrussell** [comment]
Polish is good; thanks

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/c75a95c5550ea7230b7053aa4769cce6b9545306

**Pull request closed without merging**
