### PR TITLE
Prepare for release

### PR DESCRIPTION
**Pull request by artembilan**
Change all the `BUILD-SNAPSHOT`s to their latest Milestones
Fix compatibility with those Milestones

NOTE: Would be better to merge this already after releasing Spring AMPQ 2.0.0.M1

### CODE REVIEW

**Comment by garyrussell** [comment]
org.springframework.integration.mongodb.metadata.MongoDbMetadataStoreTests > testReplace FAILED
    java.lang.UnsupportedOperationException at MongoDbMetadataStoreTests.java:136

**Comment by artembilan** [comment]
That is absolutely unclear to me how we can get `UnsupportedOperationException`  on the line of code:
```
boolean removedValue = store.replace(file1, file1Id, "4567");
```
where that `replace` has proper implementation in the `MongoDbMetadataStore` and there is any mocking or overriding in the `MongoDbMetadataStoreTests`.

**Comment by artembilan** [comment]
OK. 
Looks like everything is done.
See commits comments.

**Comment by garyrussell** [comment]
Merged as c0a507c36cbe072e72b8c460fa0c9e50e7737761

**Pull request closed without merging**
