### PR TITLE
INT-3893: UnicastReceivingChannelAdapter: fix NPE

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-3893

**Cherry-pick to ALL**

### CODE REVIEW

**Comment by artembilan** [comment]
Review with `?w=1` would be better.

**Comment by garyrussell** [comment]
Although we avoid the NPE, we could get a `RejectedExecutionException` instead.

Polishing here: RejectedExecutionException

**Comment by artembilan** [comment]
Yeah... Good catch! 
Will take into account in the future.
You can merge and cherry-pick that.

Thank you!

**Comment by garyrussell** [comment]
Merged as b62141738035d08e267202072e52da30cb996dbb and cherry-picked to all

**Pull request closed without merging**
