### PR TITLE
checkstyle FinalClassCheck

### PR DESCRIPTION
**Pull request by garyrussell**
https://sonar.spring.io/issues/search#componentRoots=org.springframework.integration%3Aspring-integration|createdAt=2016-04-02T09%3A56%3A01%2B0000|sort=UPDATE_DATE|asc=false

Notice I changed the line separators in the groovy scripts - it's not clear to me why your commits didn't add `CRLF`.

### CODE REVIEW

**Comment by artembilan** [comment]
Gary, that looks like awesome work!
I wonder when you are resting :smile: 

Would you mind to point me out for what to pay attention? 
There are so much changes, but most of them looks like just modifiers adding/remove or moving code to the proper place according the rule. Or just getting rid of asterisk imports.
So, I may miss something important to review properly.

Re.
>  it's not clear to me why your commits didn't add CRLF.

Sorry, I don't understand you here.
You made this change, for example:
```
  			.replaceFirst(/\\E20\\d\\d\(\\-20\\d\\d\)\?\\Q/, '{year}')
-			.trim() + System.lineSeparator()  + System.lineSeparator()
+			.trim() + '\n'  + '\n'
 ```
And now the result of the script looks for me on Windows like:
```
* limitations under the License.CRLF
 */LF
LF
package org.springframework.integration.amqp.channel;CRLF
CRLF
```
Instead of `CRLF` everywhere.
And looks like I can't commit this change, because of a wrong end line symbol for Git client.
WDYT?

**Comment by garyrussell** [comment]
This was easy work while I was watching golf; there's nothing really critical except this .gradle script issue.

According to the Javadocs, `System.lineSeparator()` adds CRLF on windows - since we only want Unix line breaks, it's not clear to me how these scripts will ever work as we want on Windows.

I changed them to `\n` so we'll always get that.

What am I missing?

**Comment by artembilan** [comment]
OK. Got it!
You miss here `autocrlf = true` Git option! :smile: 
> Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem. You can turn on this functionality with the core.autocrlf setting. If you’re on a Windows machine, set it to true – this converts LF endings into CRLF when you check out code:

So, please, revert ` System.lineSeparator()` code in those scripts and we'll be good to merge and live well on Windows, too.

**Comment by garyrussell** [comment]
> You miss here autocrlf = true Git option! :smile:

OK; but we need to tell developers who use windows to set that option.

Please revert during squash/merge.

**Comment by artembilan** [comment]
> but we need to tell developers who use windows to set that option.

Good, will do that in the separate commit/PR together with the code style rules as a paragraph in the `CONTRIBUTING.adoc`

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/4ac3a79df7356aad47147edad7b9581febffe1c4

**Pull request closed without merging**
