### PR TITLE
INT-4383 Expose errorChannel in EnricherSpec

### PR DESCRIPTION
**Pull request by hxc9**
JIRA: https://jira.spring.io/browse/INT-4383

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
@hxc9 ,

Thank you for the quick turnaround!

Would you mind adding some test-case on the matter, for example into the `TransformerTests`?

In addition I will ask you to update Copyright of all the affected classes to the current year. Plus add your name to the `@author` list: https://github.com/spring-projects/spring-framework/wiki/Code-Style#license

**Review by artembilan — APPROVED** [review]
OK, since you don't answer, we are taking the PR into our hands for polishing since we are going to release `5.0.1` tomorrow.

Thank you for the contribution anyway!

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/061dcb1b8787cf713ddc1231de250e51a2a72847 with the polishing for test-case: https://github.com/spring-projects/spring-integration/commit/9f6457fc313d84948cd4b70e6e41d559bdb691e8

Thank you again!

**Comment by hxc9** [comment]
Thanks for merging (and sorry about the lack of polishing, I wanted to get it done by the end of the week but you beat me to it)

**Pull request closed without merging**
