### PR TITLE
INT-4203: Expression RH Advice Improvements

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-4203

Add channel names for easier use in DSL.

Add documentation (boot) example.

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
LGTM, of course, but I wonder if we can provide some changes to those expression setters ,e.g. rename `setOnSuccessExpression(String)` to the `setOnSuccessExpressionString(String)`. And `setExpressionOnSuccess(Expression)` to `setOnSuccessExpression(Expression)`

**Comment by garyrussell** [comment]
@artembilan We could do that but we'd have to deprecate them in 4.3 and I don't think we can do that because it will cause ambiguity for XML configuration.

**Comment by artembilan** [comment]
Hm. So, we have to implement the `ExpressionEvaluatingRequestHandlerAdvice` Namespace support first of all: https://jira.spring.io/browse/INT-3596 😄 .

Well, we can do via iterative steps: 
* Introduce `setOnSuccessExpressionString(String)` and deprecate `setOnSuccessExpression(String)`  in 4.3.x
* Remove  `setOnSuccessExpression(String)`, introduce `setOnSuccessExpression(Expression)` and deprecate `setExpressionOnSuccess(Expression)` in 5.0

WDYT ?

**Comment by garyrussell** [comment]
Now should be __cherry-picked to 4.3.x__ but restore (and deprecate) the deleted messages and remove the new `set...Expression(Expression)` variants.

Let me know if you want a separate PR.

**Comment by artembilan** [comment]
No, I'm fine.
Thank you!
Just wonder what "the deleted messages" means. 
Setters ?

**Comment by artembilan** [comment]
```
org.springframework.integration.file.config.FileOutboundChannelAdapterParserTests > adapterUsageWithFailMode FAILED

    java.lang.IllegalStateException

        Caused by: org.springframework.beans.factory.BeanCreationException

            Caused by: org.springframework.beans.factory.BeanCreationException

                Caused by: org.springframework.beans.ConversionNotSupportedException

                    Caused by: java.lang.IllegalStateException
```
See Travis report.
Yeah... it's really unfortunate, but that is breaking change, right.

**Review by artembilan — APPROVED** [review]

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/77fd8a4684df7f7e54b1ff5ba86c19a55f75bafb
and cherry-picked as https://github.com/spring-projects/spring-integration/commit/3301da4157123264df1e0c7db2d4b3095edd7193

**Pull request closed without merging**
