### PR TITLE
INT-4484: Fix SyndEntryPublishedDateComparator

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-4484

Fix the `SyndEntryPublishedDateComparator` to move entries without a
date into the end of the sorted list

**Cherry-pick to 5.0.x and 4.3.x**

Fixes spring-projects/spring-integration#2473

### CODE REVIEW

**Comment by artembilan** [comment]
The issue like this might be relevant: https://jira.spring.io/browse/INT-1810...

**Comment by artembilan** [comment]
I believe this fixes spring-projects/spring-integration#2473 as well.
The `DeadlockLoserDataAccessException` is fully not related and the reported doesn't follow our recommendations about `.transactional()` for the poller. Also need to keep in mind that without TX on the poller and with the `fixedRate()` polling we definitely have concurrent INSERTs which may lead to such a dead lock.

**Comment by garyrussell** [comment]
>I believe this fixes spring-projects/spring-integration#2473 as well.

?? I created this JIRA for that issue

**Review by garyrussell — CHANGES_REQUESTED** [review]
No test case?

**Comment by artembilan** [comment]
@garyrussell ,

Anything wrong with this PR? 
It is marked for the back-port, so we can't release `5.0.6` and `4.3.17`.

Thanks

**Comment by garyrussell** [comment]
And cherry-picked as 058ae6f4c040f31617b053af9476f9aa85a02f01 and b776b14b51cc82aff4bf42906875d4546e4d55ce.

**Pull request merged**
