### PR TITLE
Remove deprecations from previous versions

### PR DESCRIPTION
**Pull request by artembilan**
* Remove Boon dependency and its usage
* Remove overloaded methods from the `IntegrationFlowDefinition`
- we can simply rely now on the super class
* Remove (or rework) deprecated entities in the docs
* Fix tests for removed deprecated APIs
* Rework affected tests to JUnit 5

### CODE REVIEW

**Comment by artembilan** [comment]
If that is really necessary I'll add `Migration Guide` page for this version.

I haven't done anything for deprecated metrics, because have no idea how to proceed.
I think those removals are related somehow to this: https://github.com/spring-projects/spring-integration/issues/2804

Thanks

**Comment by garyrussell** [comment]
Yes; I will work on that starting tomorrow - maybe won't make M1, though.

**Comment by garyrussell** [comment]
Removing legacy metrics is independent of #2804.

**Comment by garyrussell** [comment]
@artembilan 

>I haven't done anything for deprecated metrics, because have no idea how to proceed.

I looked at this some time ago; but it turns out there are some classes that will have to be removed that are NOT deprecated.

I will create a PR to deprecate all of those.

**Pull request merged**
