### PR TITLE
GH-2559: Fix InboundChannelAdapter's javadoc

### PR DESCRIPTION
**Pull request by manueljordan**
GitHub: https://github.com/spring-projects/spring-integration/issues/2559

* Fixed minor typo that does not let generate the expected javadoc
for a attribute/method

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@manueljordan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2560)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2560) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@manueljordan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2560)!

**Review by artembilan — APPROVED** [review]
Everything is good, @manueljordan , thank you!
Merging, but bear in mind that you have missed to add a proper commit message to close the issue automatically.
I've mentioned that in our discussion: https://github.com/spring-projects/spring-integration/issues/2559#issuecomment-419149859

**Comment by artembilan** [comment]
... and cherry-picked to `5.0.x`.

Looking forward for more contribution!

**Comment by manueljordan** [comment]
Seems I forget to add a line in the first post something like "Closes #2559" or "Closes: #2559", Am I correct?

But I am confused, something similar does not appear in other closed PR that I was watching prior to send this PR

**Comment by manueljordan** [comment]
I see now, that special verbs must be located in the description of the commit message too. I thought was enough in the title how I did from the beggining.

**Comment by artembilan** [comment]
Well, when we open commit history we are not going to see your description in the PR, because there is no any connection from commit to PR, if we don't specify it ourselves.
However, on the other hand, if we mention issue in the commit, such an info is going to appear on PR automatically and we don't need to modify on PR anything else.

I think you'll come to that eventually with more contributions.

**Comment by manueljordan** [comment]
Yes, more practicing :) .... thanks for your polite and valuable support

**Comment by manueljordan** [comment]
And put `GitHub: #2559` and not `Fixes: #2559` because I took how reference:

* https://github.com/spring-projects/spring-integration/pull/2538

Assuming the same approach for JIRA for GitHub..

**Pull request merged**
