### PR TITLE
GH-8730: split lock scope each lock objects in expireUnusedOlderThan to avoid holding a lock for too long

### PR DESCRIPTION
**Pull request by mhyeon-lee**
PR for: #8730

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
Thank you for reporting this and looking into possible fix!

I think that `isAcquiredInThisProcess()` impl is wrong:
```
		public final boolean isAcquiredInThisProcess() {
			return RedisLockRegistry.this.clientId.equals(
					RedisLockRegistry.this.redisTemplate.boundValueOps(this.lockKey).get());
		}
```
It's contract says "in this process". Therefore we must not look into Redis for a lock state, but rather just check `this.localLock.isLocked()`. 

The operation `expireUnusedOlderThan()` we try to fix is really just about cache for locks in the current process. We cannot effect any other processes with this cache. And even if we remove our local instance while it is locked in other process, that doesn't mean that on the next `obtain()` call, when we got a fresh local instance, we will be able to acquire a lock in Redis.

WDYT?

**Comment by artembilan** [comment]
Yeah... Looks like that is really a correct way to go.
This functionality was modeled after `ZookeeperLockRegistry`, where it does this:
```
		public boolean isAcquiredInThisProcess() {
			return this.mutex.isAcquiredInThisProcess();
		}
```
And that one is:
```

    /**
     * Returns true if the mutex is acquired by a thread in this JVM
     *
     * @return true/false
     */
    @Override
    public boolean isAcquiredInThisProcess()
```

So, please, fix this `RedisLockRegistry` to check a local lock in its `isAcquiredInThisProcess()`.

Same, please, do for the `JdbcLockRegistry`.

**Comment by mhyeon-lee** [comment]
Ok I'll try fix it.
Thank you for your review

**Comment by flex-myeonghyeon** [comment]
@artembilan I fixed it with localLock

**Review by artembilan — CHANGES_REQUESTED** [review]
Please, add your name to the `@author` list of the affected classes.
Then I'll merge.
Thanks

**Comment by flex-myeonghyeon** [comment]
@artembilan I added @author 
Thank you!

**Comment by artembilan** [comment]
... and cherry-picked to `6.1.x` & `6.0.x`.

Thank you for contribution; looking forward for more!

**Pull request merged**
