### PR TITLE
Add missing 'InputStream' in comment on FileWritingMessageHandler

### PR DESCRIPTION
**Pull request by eungjun-yi**
InputStream has been supported since 247232bdde24b81814a82100743f77d881aaf06b.

### CODE REVIEW

**Comment by garyrussell** [comment]
Please confirm that you have "signed" the CLA as [described here](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md).

Unfortunately, we need it, even for a small change like this.

Thanks

**Comment by npcode** [comment]
@garyrussell I already did it, and I have done it again just now to make sure.

**Comment by artembilan** [comment]
Hi @npcode !

Thank you for contribution even if it is so simple!

Merging but with some polishing and tricks. Because you have to raise Pull Request from top level branch, not `master`. That's why we always ask: "JIRA first!".

Please, refer to there Contribution Guideline: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/a9f50d32e449437f1142e33b7fb5ac093ac2e74e

**Comment by npcode** [comment]
Thanks for merging!

**Pull request closed without merging**
