### PR TITLE
GH-3794: Use less memory with scheduled tasks

### LINKED ISSUE #3794: Memory leak in AbstractCorrelatingMessageHandler
**In what version(s) of Spring Integration are you seeing this issue?**
SI core 5.x

**Describe the bug**
Hard references to completed and released `MessageGroup` instances stored memory by `AbstractCorrelatingMessageHandler`

**Additional details**
Please see the following discussion: https://github.com/spring-projects/spring-integration/commit/2f0b377cfb564876544c9c1d54f5a4bd5cb06f5b#r73229543, also note this is effectively a sibling of https://jira.spring.io/browse/INT-3999, the fix for which was never applied to the empty group removal logic.

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/3794

* Replace hard reference to message group with its `id` in the
`AbstractCorrelatingMessageHandler.removeEmptyGroupAfterTimeout()`
* Replace hard reference to message with its `id` in the
`DelayHandler.rescheduleAt()`

**Cherry-pick to `5.5.x`**

### CODE REVIEW

**Comment by artembilan** [comment]
I'm not sure how to test this therefore I just leave it as is with the conclusion that nothing is broken and that's it.

**Comment by garyrussell** [comment]
Not really a memory leak, right? Actually "Reduce Memory Usage with Scheduled Tasks"?

**Comment by artembilan** [comment]
Well, @vfunshteyn-zw called it a "memory leak" because their groups were scheduled for 72 hours. 
More content in the group - more memory consumption.

Anyway: we can call it whatever, but better to let GC to do its job and leave the memory for other purposes.

**Comment by garyrussell** [comment]
Right; I was just concerned that someone browses the change log.

A leak is specifically when some memory is allocated but never released.

In this case, it's unnecessary memory usage that is eventually removed.

I am ok with merging as-is, though, if you like.

**Comment by artembilan** [comment]
Fixed

**Comment by garyrussell** [comment]
...and cherry-picked.

**Pull request merged**
