### PR TITLE
(S)FTP Lambdas

### PR DESCRIPTION
**Pull request by garyrussell**

### CODE REVIEW

**Comment by artembilan** [comment]
How about my PR for the Checkstyle fixes before we go farther with similar polishings?
Thanks

**Comment by garyrussell** [comment]
Oh, right; yes, of course.

**Comment by artembilan** [comment]
LGTM.
Testing locally after rebase and with JavaDocs...

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/e5ae7d886d05331b67a122be07adc8f2f29ac901

**Pull request closed without merging**
