### PR TITLE
Enable `RedundantModifier` checkstyle, add fixer

### PR DESCRIPTION
**Pull request by artembilan**
Add `fixModifiers.gradle` to run after `check` task.

The `RedundantModifierChecker` doesn't catch all errors at once.
We need run `check -> fixModifiers` pair several times to reach `SUCCESSFUL`.

The `fixThis` has been ported from the SA, but without applying.

Review for this first of all!

### CODE REVIEW

**Comment by artembilan** [comment]
I haven't pushed fixes for easier review and the local game enjoyment :smile:

**Comment by javen-hao** [comment]
you are do the great work for public game

**Comment by garyrussell** [comment]
LGTM; although you might need the logic from `fixThis` to skip errors on this pass that are on the same line. If you have multiple errors per line on consecutive lines, the rest of this file is skipped.

Looking at your code, it looks like you could do some polishing on my `fixThis` though (e.g. `as int`) :smile:

**Comment by artembilan** [comment]
> although you might need the logic from fixThis to skip errors on this pass that are on the same line.

I tried to fix all errors for the same line, but even with `ignoreFailures = true` the `RedundantModifierChecker` stops scanning if it has found an error in the line already.

See my comment above and `while (error && ln == (error.@line as int))` in the script. 
We have to re-run the check -> fix cycle several times if we have something like `public abstract` on the interface method, like in the `ScriptExecutor`.

Yes, `fixThis` will be the next one.

So, if you are fine with this I'm pushing ti master with the fix for all those `redundant modifier` vulnerabilities.

Since we have enough scripts already we may consider to start a new project for them or study how to write Gradle plugins and add one for these kind of task in to the https://github.com/spring-projects/gradle-plugins.

CC @rwinch

**Comment by garyrussell** [comment]
Well, with fix this, if we saw:

    foo = bar
    baz = qux

The this rule reported 4 errors; to make life simpler I skipped over the bar error and fixed the baz error in the first pass. Without the skip, the rest of the file is skipped and we needed many passes.

With that skip logic we only need as many passes as there are violations on a single line.

We can put a formal project on the back-burner; I'd prefer to spend time to fix our violations before spending time on that.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/c2954881ad59c1fc2926e37a581cb4ed5949d53d

**Pull request closed without merging**
