### PR TITLE
[INT-3666] - Implementation of Metadastore for MongoDB

### PR DESCRIPTION
**Pull request by senthilaru**
[INT-3666] - Implementation of Metadastore for MongoDB

### CODE REVIEW

**Comment by artembilan** [comment]
@senthilaru , thank you for the contribution, but to accept your work we should be sure that you have signed CLA (https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md).

From other side this PR is bad, because you can't PR from the `master` branch. You should create a new one (e.g. `INT-3666`) based on the up-to-date `master`.

**Comment by garyrussell** [comment]
Thanks for your contribution; as @artembilan says, we need a "signed" CLA so we can look at your work.

Regarding the branch, please refer to the [A Day in the Life of a Contributor](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md#a-day-in-the-life-of-a-contributor) in the contributing guidelines.

**Comment by senthilaru** [comment]
I have created another PR in a different branch. (https://github.com/spring-projects/spring-integration/pull/1397)

I have signed and agree to the terms of the SpringSource Individual
Contributor License Agreement.

**Comment by artembilan** [comment]
Closed in favor of #1397

**Pull request closed without merging**
