### PR TITLE
Add Java DSL `.fluxTransform(Function)` operator

### PR DESCRIPTION
**Pull request by artembilan**
For better interoperability with Reactor `Flux` from the
end-user perspective introduce an operator which could
call a target `Function` with integration data wrapped to the `Flux`
and expect a `Publisher<?>` result to continue the flow.
This way end-user just needs to implement a `Function` (or method)
to accept the `Flux` as an input and return some `Publisher`
after the sequence of reactive operators.

Such a new operator also allows a smooth integration with the
Spring Cloud Function, where it is just enough to lookup the function
in the catalog and inject it into this operator

### CODE REVIEW

**Comment by artembilan** [comment]
@olegz ,

This is what we talked about how to avoid extra call for the `source.output()` when we mix Spring Integration Java DSL and Spring Cloud Function.
Also pay attention how I use `Mono.subscriberContext()` to propagate a `requestMessage` to be used for building reply message.

Let me know WDYT!

Thank you

/CC @smaldini

**Comment by garyrussell** [comment]
Please update the commit comment with rationale.

**Comment by artembilan** [comment]
Pushed. 
Thank you for the pointer!

**Comment by olegz** [comment]
FWIW, I know Gary already merged it, but as Artem said this came up as he was reviewing one of the PRs for SCSt/SCF integration work, so I can definitely use it now.

**Pull request merged**
