### PR TITLE
correcting the link from java-dsl-gateway to dsl

### PR DESCRIPTION
**Pull request by harryalto**
java-dsl-gateway doesnt seem to exist

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@harryalto Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2641)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2641) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@harryalto Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2641)!

**Comment by artembilan** [comment]
Not sure what version you mean, but the paragraph is definitely there with the proper link: https://docs.spring.io/spring-integration/docs/5.0.9.RELEASE/reference/html/java-dsl.html#java-dsl-gateway.

And it also works well in the current version we are going to release tomorrow: https://docs.spring.io/spring-integration/docs/5.1.1.BUILD-SNAPSHOT/reference/html/java-dsl.html#java-dsl-gateway

Please, elaborate more what is going on and what make you think it is broken.

Thank you!

**Comment by harryalto** [comment]
@artembilan : first of all thanks for pointing me to the correct link for java-dsl-gateway. I will correct the PR 
The issue i was facing was..when i was clicking the link  [java-dsl-gateway](https://github.com/spring-projects/spring-integration/blob/master/src/reference/asciidoc/gateway.adoc#java-dsl-gateway) it wouldnt redirect me to the link as it tries to look for the references within the doc.

**Comment by artembilan** [comment]
Still, not sure what is your concern. there is just no `java-dsl-gateway` section in the `gateway` chapter.

Those links just don't work on multi gh-pages.
Our aim is ASCiIDoc and generated HTML and PDF.

We can think about improving those adocs directly on GitHub, but that's fully not related what you claim in this PR.

**Comment by garyrussell** [comment]
They are just raw asciidoc pages; use the [assembled reference manual instead](https://docs.spring.io/spring-integration/reference/html/).

**Pull request closed without merging**
