### PR TITLE
Update Tomcat to 8.5.6

### PR DESCRIPTION
**Pull request by garyrussell**
Align with Boot 2.0

### CODE REVIEW

**Comment by artembilan** [comment]
LGTM.
Since I did locally the same but with some other upgrades (no breaking changes), I'll merge your PR together with my fixes. 😄

**Comment by garyrussell** [comment]
ok; notice the tomcat version was out of place.

**Review by artembilan — APPROVED** [review]
And will fix `@Copyright` on merge 😄

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/4c462a897270140d030bec3f0ea7b580c782e353

**Pull request closed without merging**
