### PR TITLE
Fixing IllegalStateException when duplicate cookie names are in the request

### PR DESCRIPTION
**Pull request by Anthonyas007**
Potential fix for the issue I submitted earlier this evening: https://github.com/spring-projects/spring-integration/issues/3641

Just thought I would help speed things up if you decide to address it :)

Also the unit test serves as an example of the issue

### CODE REVIEW

**Comment by artembilan** [comment]
@Anthonyas007 Please sign the Contributor License Agreement!
Otherwise we cannot review your fix and would need to close the PR eventually.

See the message from Pivotal CLA above.

Thanks for understanding.

**Comment by artembilan** [comment]
No problem, @Anthonyas007 !

We still have time to fix this until the next week for releases.
Did you see my comments on the issue?
Any thoughts?

Thanks

**Comment by Anthonyas007** [comment]
@artembilan Yes, I saw the comments on GH-3641 . I like the MultiValueMap approach. 1) It is consistent with other APIs 2) It is closer to the HTTP spec and 3) it allows access to all cookies in the eval context. 
Is the next step for me to make the changes and update this pull request? FYI - This is the first time I have contributed to an open source project so please bear with me

**Comment by artembilan** [comment]
Correct. Just make a respective change and push commit.
Also add you name to all the affected classes in the `@author` section 😄

**Comment by Anthonyas007** [comment]
Awesome, I should be able to get this to you by the weekend (possibly later this evening). I'll be out of town tomorrow-Sunday, but I am bringing my laptop with me and will have time :)

**Comment by artembilan** [comment]
No problem!
Take your time!
The release is on next Tuesday: https://calendar.spring.io/

**Pull request closed without merging**
