### PR TITLE
INT-4241: JsonPropertyAccessor cannot return array values

### PR DESCRIPTION
**Pull request by pgpx**
JIRA: https://jira.spring.io/browse/INT-4241

Prototype tests and code to show how JSON (Jackson) ArrayNodes could be returned from Spring Expressions.  If you think it is a worthwhile change, then it is probably worth adding some more tests (and documenting the wrap object or finding an alternative for root array objects).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pgpx Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2084)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2084) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pgpx Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2084)!

**Comment by artembilan** [comment]
Thank you for the effort, @pgpx , but sorry: I still have difficulties to understand the problem.
Would you mind to share some code to demonstrate what you expect, but it doesn't work.

You did a lot of changes in the `JsonPropertyAccessorTests`, so I'm just loosing context a bit. 😄

**Review by artembilan — APPROVED** [review]
LGTM
Merging with some polishing...

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/85aead337f9063fdfcd41ee230765e89ea99a7cf.

@pgpx ,
thank you for contribution.
Looking forward for more!

**Pull request closed without merging**
