### PR TITLE
Prepare Master for 4.3

### PR DESCRIPTION
**Pull request by garyrussell**

### CODE REVIEW

**Comment by artembilan** [comment]
Everything looks good (running `testAll --parallel` to confirm).
But I wonder if you are going to fix `whats-new.adoc` and `changes-4.1-4.2.adoc` according to the `4.3` fix.
I can do that on merge, BTW, if you are busy.

P.S. All other `@Deprecated` removal can be done during appropriate JIRA: https://jira.spring.io/browse/INT-3665

**Comment by garyrussell** [comment]
Yes, I thought about that this morning - if you have to leave, go ahead and merge and I'll push a separate commit for that.

**Comment by artembilan** [comment]
Don't worry I can do that right now.

```
BUILD SUCCESSFUL

Total time: 9 mins 57.676 secs
```
BTW

**Comment by artembilan** [comment]
Here is a polishing https://github.com/artembilan/spring-integration/commit/de7f8cd1dba2743519b4c615e02a05485eca8f8d.
I have the low battery, so merging. If that you can fix and push directly.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/051b393ed03ec2391a8ceb1e2095ca1d59f44d47

**Pull request closed without merging**
