### PR TITLE
INT-3841: Fix NPE in the `AmqpChannelFactoryBean`

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-3841

Previously the `isPubSub` was as `Boolean` object and `null` by default.
Convert it to the primitive to achieve the `false` logic by default as expected.

### CODE REVIEW

**Comment by artembilan** [comment]
Even if it isn't cherry-picked properly, I consider it as a candidate for backporting until `3.0.x`.

**Comment by garyrussell** [comment]
Already pushed to master but when testing in 4.1.x `ChannelTests.pubSubLostConnectionTest()` is failing - also fails on master.

Investigating...

**Comment by garyrussell** [comment]
Due to new test - needs `@DirtiesContext(classMode=ClassMode.AFTER_EACH_TEST_METHOD)`


Pushing...

**Comment by artembilan** [comment]
Good. 
Thank you @garyrussell !

**Pull request merged**
