### PR TITLE
Make Headers PREFIX Constants Public

### PR DESCRIPTION
**Pull request by garyrussell**
**cherry-pick to 5.0.x**

### CODE REVIEW

**Comment by jmax01** [comment]
Great! Thank you.

**Review by artembilan — COMMENTED** [review]
I believe an `IpHeaders` should be included to this fix as well.

I can fix on merge though...

**Comment by garyrussell** [comment]
Ah; yes; didn't show up in my search because it's not PREFIX.

Yes, please fix on merge.

**Comment by garyrussell** [comment]
(Please change to `PREFIX`).

**Comment by artembilan** [comment]
> (Please change to PREFIX).

We can't see its source code:
```
public final class IpHeaders {

	private static final String IP = "ip_";

	private static final String TCP = IP + "tcp_";
```

Although it's indeed can be like `IP_PREFIX` and `TCP_PREFIX`  😄

**Comment by garyrussell** [comment]
hehe - ok (or leave as-is).

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/5ab7d2493478d4193b64bd26abf6ec300539ed2b and cherry-picked to `5.0.x`

**Pull request closed without merging**
