### PR TITLE
Fixes issues/2340 WebFluxMessageHandlerSpec should support chaining

### PR DESCRIPTION
**Pull request by asarkar**

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
Cool!

Any chance to have some simple test-case modification for confirmation? See `WebFluxDslTests`.

Plus your name to the `@author` list for each affected class and also would be great to have a proper commit message: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc#provide-a-link-to-the-jira-issue-in-the-associated-pull-request

You can reject all the request from and I'll fix everything during merge.

Thank you!

**Comment by asarkar** [comment]
Added my name to author list, and updated commit message. Tests for those 2 methods don't exist, so it seems like outside the scope of this PR to add new ones.

**Comment by artembilan** [comment]
Well, definitely yes, it is the scope of this PR. Since we hadn't had tests before we have bumped to this issue.
So, if we are fixing it here, let's do that proper way do not come back to the problem anymore.

Moreover the rule is like: any PR should be supplied with tests or should provide a confirmation that existing tests cover the fix.

On the other hand we don't need extra test. I believe that we can modify existing tests at least to call these method for confirmation that the method chain issue is covered by test suit.

WDYT?

Thanks for understanding.

**Comment by asarkar** [comment]
I don't think it's fair to force me to write tests that someone else didn't, but I'm waiting to get my code working with this fix, so I'll try to add tests and report back.

**Comment by asarkar** [comment]
I wrote a test (see attached) but it keeps failing, and being new to the codebase, I'm not exactly sure why. This is taking longer than I expected, so if this can't be fixed quickly, I'll bail. If that means the PR can't be merged, so be it.
[WebFluxDslTests.txt](https://github.com/spring-projects/spring-integration/files/1654005/WebFluxDslTests.txt)

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/56ffed080120ebb32c2e9e8db39388cfe85ad989.

@asarkar ,

Thank you for your effort!
I've utilized something from your test-case and minimized it to exactly the feature we would like to test.

Looking forward for more from you!

**Pull request closed without merging**
