### PR TITLE
INT-4019: Upgrade to Gradle-2.13

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INT-4019
- Add `org.gradle.daemon=true` to `gradle.properties`
- Add `--no-daemon` to CI plans, such as `master` and `nightly`
- Adjust `.travis.yml` to disable `gradlew assamble` task and allow artifacts caching

### CODE REVIEW

**Comment by artembilan** [comment]
That's all.
I don't know what to do here else.

I haven't finished reading Cedric's article, but looks like everything rest is just a note how they are cool :smile:

**Comment by manueljordan** [comment]
Should I wait this merge?

**Comment by artembilan** [comment]
Hello @manueljordan !

Thank you for your attention and here, too :smile: 

No, it doesn't relate to your work. 
It is fully different story. We linked previous tasks with your one just because you have been forced to `@Ignore` tests.
Pay attention that Gary's PR about `Stream Remote Adapters` has been merged without involving you.

As Gary said in the `merge/rebase` email, we do the proper re-ordering and accumulation during merge.
If there is need from your side, we'll let you know.

Although you feel free to review the PR and leave your feedback if that :wink:

**Comment by garyrussell** [comment]
Merged as ca0fa1b182112200e40dacce380c8e02d20d5bcf

**Pull request closed without merging**
