### PR TITLE
Added setShouldAppendNewLine(boolean shouldAppendNewLine) method to the FileWritingMessageHandler class.

### PR DESCRIPTION
**Pull request by tonyfalabella**
Added `setShouldAppendNewLine(boolean shouldAppendNewLine)` method to the `FileWritingMessageHandler` class.  Added similar test methods to the `FileWritingMessageHandlerTests` class.

See http://stackoverflow.com/questions/27320479/add-setshouldappendnewline-to-filewritingmessagehandler-in-spring-integration

### CODE REVIEW

**Comment by artembilan** [comment]
@tonyfalabella , before we'll take a look to your work, let us know if you have signed CLA: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md.
Thanks

**Comment by tonyfalabella** [comment]
Yes I thought I signed this last month but just in case I signed it again. 

"Your confirmation number is 106020150125104428"

**Comment by artembilan** [comment]
Thanks, @tonyfalabella .

We are to merge and backport it, but Namespace attribute for the new 4.2 version should be addressed in the separate JIRA.

**Comment by tonyfalabella** [comment]
Please see https://jira.spring.io/browse/INT-3621 for the XML namespace support.

**Comment by artembilan** [comment]
@tonyfalabella , I have a different solution on the matter: https://github.com/artembilan/spring-integration/commit/473e2f5febe71e210da7892658344a3979c0e7ab
It is polishing to your commit.
As you see I accept `appendNewLine` only for `FileExistsMode.APPEND` mode and add it to the `File` `payload` case too.
IMO it doesn't make sence to handle `appendNewLine` if we just right to the file a fresh content. I expect to see it like I send it. From other side `APPEND` is a different mode and it really should be handled like `CharacterStreamWritingMessageHandler` case.

Anyway I'm open for discussion.

Thank you for contribution! Feel free to go ahead with Namespace support, when this one will be merged.

/CC @garyrussell

**Comment by tonyfalabella** [comment]
Will attempt to work on the Namespace support for this tonight. @artembilan @garyrussell

**Comment by artembilan** [comment]
@garyrussell , would be great, if you'd take a look to this PR for double checking and we go ahead with @tonyfalabella for his second dependant PR #1363 .

Thank you both!

**Comment by garyrussell** [comment]
@artembilan Looks good to me except I don't think we should limit the functionality to APPEND only; while I agree it really only makes sense in the APPEND case, consider an application that wants to start a new file (via sending to an adapter configured with REPLACE) followed by a bunch of APPENDs.

**Comment by artembilan** [comment]
Thank you @garyrussell ! OK. I won't mind for that case too. Is you position that this `appendNewLine` should be for all supported `payload` types ?

**Comment by artembilan** [comment]
Here you are regarding our last comments: https://github.com/artembilan/spring-integration/commit/6e5a5161edc823f8c5c3de8d3ebce91380fa67de

**Comment by garyrussell** [comment]
I don't see why not, given it's new and defaults to `false`. Unless you have some argument otherwise?

**Comment by artembilan** [comment]
According to the private discussion with @garyrussell , the last polishing looks good. So, merging...
After that I'll take a look to your #1363 , @tonyfalabella .

Thank you very much for the contribution!

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/24beee96272aaa1c6a242fde95fdff0f9cc75f60 and cherry-picked

**Pull request closed without merging**
