### PR TITLE
added a missing double quote 

### PR DESCRIPTION
**Pull request by nadavc**

### CODE REVIEW

**Comment by garyrussell** [comment]
Thanks; while it might seem a little onerous, we need you [to "sign" the CLA](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement); to merge even a trivial change like this.

**Comment by nadavc** [comment]
Thanks, Gary. I have signed and agree to the terms of the SpringSource Individual
Contributor License Agreement.

**Comment by artembilan** [comment]
That's great!
So, merging...

Thank you very much and looking forward for more contribution!

**Comment by artembilan** [comment]
Merged after rebase

**Pull request closed without merging**
