### PR TITLE
INT-3826: Fix @EnableIntegrationManagement

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-3826

Application Context would not initialize with annotation without attributes.

Defaults were wrong; metrics factory bean name.

### CODE REVIEW

**Comment by artembilan** [comment]
@garyrussell , please, take a look to the polishing: https://github.com/artembilan/spring-integration/commit/9e05707fb5e3f83fe5ee4d854bc20fa68ed23f65.

**Comment by garyrussell** [comment]
It's not entirely clear to me why that polish was needed but I am ok with it.

**Comment by artembilan** [comment]
Well, I'm also barely sure that someone is going to use that class as top level bean, not like a part of `@EnableIntegrationManagement` or `<int:management>`, but let's just make it robust and don't override anything explicit by some string which may not be as a bean at all...

So, merging since you agreed

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/13b40376c0382dcec9b215b7e14cf82e40b8dc6e

**Pull request closed without merging**
