### PR TITLE
MessagingGateway default errorChannel

### PR DESCRIPTION
**Pull request by pomverte**
set the default errorChannel to send all error message to the global default errorChannel

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pomverte Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=1865)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=1865) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by garyrussell** [comment]
Thanks for the contribution, but this is not an appropriate change - the default behavior for a gateway is to throw the exception to the caller (any `MessagingException` is unwrapped and the underlying cause is thrown.

Including this change would be a huge behavior change - to simply log and ignore the exception.

We also cannot accept any PRs until you "sign" the CLA; we also need test case(s) for all changes; please refer to the [contribution guidelines](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc).

**Comment by garyrussell** [comment]
Please note that with the current version of Spring Integration (and Spring Framework), you can achieve your desired result by copying the `MessagingGateway` annotation and meta-annotating it with `MessagingGateway` ...

	@Target(ElementType.TYPE)
	@Retention(RetentionPolicy.RUNTIME)
	@Documented
	@MessagingGateway
	public @interface ErrorChannelGateway {

            ...

            String errorChannel() default "errorChannel";

            ...

	}

and

	@ErrorChannelGateway(defaultRequestChannel = "foo")
	public interface MyGate {

		void foo(String foo);

	}

**Comment by pomverte** [comment]
Okay thank you for the precision
Cheers !

**Pull request closed without merging**
