### PR TITLE
INT-4037: Graph: Add Link Type To LinkNode

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-4037

Provide type information in `LinkNode`s, input, output, error, discard.

This might be rendered as:

```
              +---(discard)
              |
         +----o----+
         |         |
         |         |
         |         |
(input)--o         o---(output)
         |         |
         |         |
         |         |
         +----o----+
              |
              +---(error)


  "links" : [ {
    "from" : 10,
    "to" : 9,
    "type" : "output"
  }, {
    "from" : 10,
    "to" : 1,
    "type" : "error"
  } ]

```

### CODE REVIEW

**Comment by artembilan** [comment]
I think I'm fine with the solution.
The `MessageChannelNode` really can be visualized with both its link types on its ends.

I can merge it and reflect in my documentation PR, since it isn't merged yet.
Or I can wait for you here, if the situation is otherwise :smile:

**Comment by garyrussell** [comment]
Of course, links of type `input` connect from the right port of the channel node to the left port of the consuming node.

**Comment by artembilan** [comment]
I'm fine to merge this PR together with the Docs fixing for this new link type feature.
Maybe even including your ASCII art :smile: 
Let me know if you are going to do that yourself or leave it to me as a polishing task.

**Comment by garyrussell** [comment]
Thanks, I forgot I already merged your PR - please do the polish - thanks.

**Comment by artembilan** [comment]
@garyrussell , here is a polishing which we have talked about: https://github.com/artembilan/spring-integration/commit/c2244713083e26f1c969af737fd0e6fff324773b

**Comment by garyrussell** [comment]
Looks good; thanks.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/e4d2484db61f1763621e91d21259f29ee7bc1ad3

**Pull request closed without merging**
