### PR TITLE
INT-3956 use Deque.peekLast() for timeSinceLastSend on channel metrics.

### PR DESCRIPTION
**Pull request by sworisbreathing**
I had to change the visibility modifiers of a couple of internal fields in order to make the tests accurate. Hope that's okay.

### CODE REVIEW

**Comment by sworisbreathing** [comment]
:-(
The travis build didn't fail during compilation or tests, so I'm not sure what's going on. Will close and reopen to try and kick off another build.

**Comment by sworisbreathing** [comment]
Okay, looking back over the build history in Travis, I can see that the builds started failing well before I made this PR. Since gradle is failing with error 137 and this is a rather large project, my guess is the failures are due to the build trying to gobble up more memory than the maximum limit in Travis (https://github.com/travis-ci/travis-ci/issues/2882).

**Comment by garyrussell** [comment]
@sworisbreathing 

Yes; there's something wrong with the doc build on travis (only started failing recently); we haven't been able to figure out how to set --debug on the `./gradlew assemble` that travis does before executing our script. :frowning: 

Thank you for your contribution; before we can look at it we need you to "sign" the CLA (and confirm you have done so here) - see the [contribution guidelines](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc). 

Thanks again!

**Comment by garyrussell** [comment]
>Hope that's okay.

BTW, we generally use `TestUtils.getPropertyValue(object, "name", Deque.class)` (reflection) rather than change field visibility just for tests.

**Comment by artembilan** [comment]
@sworisbreathing , thank you for the contribution!

And especial thanks for the attention to that our Travis failure.
If you see any solution there as well, you can just push it here in your PR.

To be honest I don't see useful info following your link. Everything looks in a mess and specific to those particular projects. I'm not sure that switching off services is a good way to go. I'm sure eventually we may need all of them. Not only RabbitMQ, Redis and MongoDB, as we have now...

**Comment by sworisbreathing** [comment]
@garyrussell - I tried to sign the CLA before opening the PR, but it told me I'd already done so (confirmation number 144520151019102152). I'll push an update in a couple hours, once I get into the office, to revert the visibility changes and use the reflection utility instead.

@artembilan - happy to help. Re: the travis failure, the common theme in all of those projects is that they exceed either a memory limit or some kind of timeout value. I noticed the build for Spring-XD calls `travis_wait ./gradlew ...`, and it also caches `$HOME/.gradle/`. Maybe that would help?

**Comment by artembilan** [comment]
`travis_wait`... That's funny.
But let's give it a shot!

In the PR #1716 we was forced to exclude `reference` task from the Travis process and looks like we are happy.
We discussed with @garyrussell that there is really no memory impact from our side, plus we use `sudo: false`, so no any extra services for our image.

From other side let's stop to disturb this PR about the Travis issue and move the conversation to that one.

Thank you for the CLA confirmation! Now we are free to review your PR and merge, if that.

**Comment by sworisbreathing** [comment]
@garyrussell @artembilan - I've updated the PR to use reflection. Let me know if there is anything else you need from my end.

Once I have bandwidth, I'll see about putting together a plugin for Spring-XD to use the updated code in the 1.3 release.

**Comment by garyrussell** [comment]
Thanks again!!

>Once I have bandwidth, I'll see about putting together a plugin for Spring-XD to use the updated code in the 1.3 release.

I am not sure what you mean; we will release 4.2.5 soon and bundle it with 1.3.1 (due next week).

In the meantime, you should be able to simply replace the SI 4.2.4 jars in xd/lib with the snapshots.

**Comment by sworisbreathing** [comment]
> I am not sure what you mean; we will release 4.2.5 soon and bundle it with 1.3.1 (due next week).

What I mean is, I'm running Spring-XD 1.3.0 and even if 1.3.1 is released next week, it could be a while before I can upgrade. Installing a new plugin to a running production system is easier for me to schedule than an upgrade of the system itself :-)

> In the meantime, you should be able to simply replace the SI 4.2.4 jars in xd/lib with the snapshots.

Spring-XD 1.3.0 uses SI 4.2.2, so I'd want to build off that release branch instead of 4.2.4. Probably would be easier than writing a plugin though :-)

**Comment by garyrussell** [comment]
Thanks; that makes sense; building on top of the v4.2.2.RELEASE tag would certainly be safest; I think the risk is low; we are very conservative with changes in point (4.2.x) releases but I understand your concern.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/bfb31a13615d648a5c80ea3f81d06959784bdfb5 and cherry-picked.

@sworisbreathing , thank you for contribution. Looking forward for more!

Please, review the commit. There are just minor fixes to the core code, like your name in the author list.
And I made test-case `Thread.sleep()`-"free". It's very dangerous to rely on that when we run project in the heavy duty environment like Bamboo.

**Comment by sworisbreathing** [comment]
@artembilan - the code looks good to me, and thanks for the author tags

Only slightly minor concern is the comments in the tests still mention that we've called `Thread.sleep()`, but it's obviously not a show-stopper :-)

**Comment by artembilan** [comment]
Yeah... Before changing the code I decided to leave your comment. You spent time for that.
And right, sometimes it's difficult to understand the algorithm, therefore similar comment are really useful.
But when I made the test passed after several failures, I was so happy that forgot to polish comment.

We may fix it eventually or will live with that forever if test passes all the time :wink:

**Pull request closed without merging**
