### PR TITLE
Add ObservationRegistry option to JmsListenerContainerSpec

### PR DESCRIPTION
**Pull request by nightswimmings**
https://github.com/spring-projects/spring-integration/issues/8734

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
We cannot review this without signed CLA.
Plus I believe we need some test verification in the `JmsTests` to be sure that this observation configuration has an effect on the flow.

Thanks

**Comment by artembilan** [comment]
Superseded with https://github.com/spring-projects/spring-integration/pull/8764

**Comment by nightswimmings** [comment]
Im really sorry, I jsut saw this, I thought it was abandoned as another user said in another issue that he would take care of the issue because it was related to other considerations. I can't find the comment though (was it deleted on the mother issue?)

**Comment by artembilan** [comment]
@nightswimmings ,

There was no such a comment: only your this PR.

We were a bit short in time for yesterday's release, so I decided to fix it my own.

You always can look into our backlog to work on something what is interested for you.

Thank you for your effort anyway!

**Pull request closed without merging**
