### PR TITLE
INT-3799: Fix Tangles

### PR DESCRIPTION
**Pull request by garyrussell**
Part 1 - eliminate references from support to other packages

Part 2 - handler to aggregator/router
- move BarrierMH to aggregator
- Fix ScatterGather references

Part 3 - move TrackableComponent
- to support.management

Part 4 - class tangles
- TcpConnectionServerExceptionEvent
- RecipientListRouterManagement

### CODE REVIEW

**Comment by artembilan** [comment]
Nothing to complain about.
I'll check with IDEA Dependencies Matrix tool and merge later.

**Comment by artembilan** [comment]
From one side nothing to complain about, but from other side I wonder, if we should check our Reference Manual for these changes and fix it as well...

BTW, `whats-new.adoc` has a typo: o.s.integ~~t~~**r**ation.util.FunctionIterator

**Comment by garyrussell** [comment]
I didn't see any references to the moved classes in the `*.adoc`.

I pushed a fix for the typo

**Comment by artembilan** [comment]
Good. Merging...

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/4ab25121afbab77f0d018835a52b0e80b47a1d35

**Pull request closed without merging**
