### PR TITLE
Fix missing space in doc

### PR DESCRIPTION
**Pull request by alexsderkach**

### CODE REVIEW

**Comment by artembilan** [comment]
Hello @alexsderkach !

How about for signing CLA: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc? 

Thank you for fixing and contribution at all!

**Comment by alexsderkach** [comment]
Hi @artembilan 
Signed :+1:

**Comment by artembilan** [comment]
Great! I've just received the confirmation for your signed CLA.
So, reviewing and merging...

**Comment by artembilan** [comment]
Merged after rebase.

Thank you one more time, Sasha, for contribution. Looking forward for more!

Дякую!

**Comment by alexsderkach** [comment]
@artembilan Будь-ласка :)

**Pull request closed without merging**
