### PR TITLE
Issue #254  migrate smb extension repo into spring integration main repo

### PR DESCRIPTION
**Pull request by GregBragg**
@artembilan as discussed in Spring Integration Extensions repo for Issue https://github.com/spring-projects/spring-integration-extensions/issues/254

### CODE REVIEW

**Comment by artembilan** [comment]
@GregBragg ,

please, consider to rebase your branch to the latest `main`: there is a fix for broken API from upstream dependency.

I will look into this tomorrow then.

Thank you!

**Review by artembilan — CHANGES_REQUESTED** [review]
A couple not critical, but useful pointers:

1. Why "merge"? Why everyone does "merge", when I am clearly asking to do a `rebase`. Your change might be more actual, than what you pull from the `main`.
2. The commit message is important, at least the first one: https://cbea.ms/git-commit/
3. We don't use JUnit asserts any more. `AssertJ` is the library we rely on. I'm not sure if this PR is going to fail against our Checkstyle rules on the matter, but there is an IntelliJ IDEA plugin to migrate smoothly: https://plugins.jetbrains.com/plugin/10345-assertions2assertj
4.  All these classes are new for this project, so their `@since` must be `6.0`. Can be done in the new PR if this is a lot of burden for the current one.
5. The Copyright date must be updated to the current year.
6. Did you run `./gradlew clean :spring-integration-smb:check` locally?
7. We will need a documentation for this new module. Yes, another PR would be better.

I think that's it. As far as this PR is green, I'm merging.

Thank you!

**Review by artembilan — CHANGES_REQUESTED** [review]
Right, Checkstyle has just failed:
```
 > Task :spring-integration-smb:checkstyleTest FAILED
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/AbstractBaseTests.java:19:31: Using a static member import should be avoided - org.junit.Assert.assertNotNull. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/AbstractBaseTests.java:20:31: Using a static member import should be avoided - org.junit.Assert.assertTrue. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/SmbMessageHistoryTests.java:19:31: Using a static member import should be avoided - org.junit.Assert.assertEquals. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbInboundChannelAdapterParserTests.java:19:36: Using a static member import should be avoided - org.hamcrest.Matchers.instanceOf. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbInboundChannelAdapterParserTests.java:20:31: Using a static member import should be avoided - org.junit.Assert.assertEquals. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbInboundChannelAdapterParserTests.java:21:31: Using a static member import should be avoided - org.junit.Assert.assertNotNull. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbInboundChannelAdapterParserTests.java:22:31: Using a static member import should be avoided - org.junit.Assert.assertThat. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbInboundChannelAdapterParserTests.java:23:31: Using a static member import should be avoided - org.junit.Assert.assertTrue. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbInboundOutboundSample.java:19:31: Using a static member import should be avoided - org.junit.Assert.assertTrue. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbOutboundChannelAdapterParserTests.java:19:31: Using a static member import should be avoided - org.junit.Assert.assertEquals. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbOutboundChannelAdapterParserTests.java:20:31: Using a static member import should be avoided - org.junit.Assert.assertNotNull. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbOutboundChannelAdapterParserTests.java:21:31: Using a static member import should be avoided - org.junit.Assert.assertSame. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/config/SmbOutboundChannelAdapterParserTests.java:22:31: Using a static member import should be avoided - org.junit.Assert.assertTrue. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/session/SmbSessionFactoryWithCIFSContextTests.java:20:31: Using a static member import should be avoided - org.junit.Assert.assertNotNull. [AvoidStaticImport]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-smb/src/test/java/org/springframework/integration/smb/session/SmbSessionTests.java:19:31: Using a static member import should be avoided - org.junit.Assert.assertEquals. [AvoidStaticImport]
```

Please, consider to migrate to AssertJ as I explained before.

**Comment by artembilan** [comment]
You can find docs in the `spring-integration\src\reference\asciidoc` dir.
So, we would need to create an `smb.adoc` file and include it into the `index.adoc` and `index-single.adoc`.
Then mention as a `New Component` in the `whats-new.adoc`.
In the end it also would be great to add SMB channel adapters into the `endpoint-summary.adoc`.

But as I said: separate PR and so on.

**Comment by GregBragg** [comment]
Ok np, working on the changes now for AssertJ and the others... Thanks!

**Review by artembilan — APPROVED** [review]
LGTM

Pulling locally for final review, clean up and merge.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/7ad71d38d92a58d92690e3745a18ff5c4150bc3a.

@GregBragg ,

thank you again for contribution; feel free to go ahead with the docs PR!

**Pull request closed without merging**
