### PR TITLE
INT-4101: Default poller to issue proper MessagingException

### PR DESCRIPTION
**Pull request by m-terra**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@andybaer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=1897)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=1897) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@andybaer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=1897)!

**Comment by artembilan** [comment]
Hello, @andybaer !

Thank you for contribution, of course!

But there is to fix something else with your PR: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc.

The main my concern right is that you have to PR it against the current `master`, not `4.3.x`. And that is how `INT-4101` points - `5.0`. And yes, do that against top-level branch. Read carefully that "Contributor Guidelines".

**Comment by andybaer** [comment]
moving to master branch

**Pull request closed without merging**
