### PR TITLE
INT-4069: Use AnnotatedElementUtils

### PR DESCRIPTION
**Pull request by ghchapman**
JIRA: https://jira.spring.io/browse/INT-4069

Finding annotations with AnnotatedElementUtils allows us to use
explicit annotation attribute overrides specified by the @AliasFor
annotation.

### CODE REVIEW

**Comment by ghchapman** [comment]
There are other usages of AnnotationUtils.findAnnotation, both in MethodAnnotationPublisherMetadataSource.java (e.g. line 81) and in the wider spring integration project.  With regards to the one in MethodAnnotationPublisherMetadataSource.java, it would be redundant to call the AnnotatedElementUtils method as the Payload annotation can't be a meta annotation.  However, it could be argued that for the sake of consistency (and the fact that Payload could become a meta annotation), that could be a call to the AnnotatedElementUtils method as well.

With regards to the other usages of AnnotationUtils.findAnnotation, would changes to these be considered on a case by case basis?

**Comment by artembilan** [comment]
Thank you for contribution @ghchapman !

Please, run the project locally before pushing:

```
:spring-integration-core:checkstyleTest[ant:checkstyle] [ERROR] /home/travis/build/spring-projects/spring-integration/spring-integration-core/src/test/java/org/springframework/integration/aop/MethodAnnotationPublisherMetadataSourceTests.java:136:17: '}' at column 3 should be alone on a line. [RightCurly]
```
You may find some interesting effects :smile: 
For this purpose we use 
```
gradlew clean check --parallel
```
to be sure that your changes to core module don't break anything.

Well, looking to your changes we may even accept it into the current `4.3.1` point release, rather than wait for the next major `5.0`. 

But...

Not sure what to say you about all other `AnnotationUtils.findAnnotation`, because even Spring Framework didn't get rid off it everywhere. for example `AnnotationJmxAttributeSource`:
```
public org.springframework.jmx.export.metadata.ManagedResource getManagedResource(Class<?> beanClass) throws InvalidMetadataException {
	ManagedResource ann = AnnotationUtils.findAnnotation(beanClass, ManagedResource.class);
...
public org.springframework.jmx.export.metadata.ManagedAttribute getManagedAttribute(Method method) throws InvalidMetadataException {
	ManagedAttribute ann = AnnotationUtils.findAnnotation(method, ManagedAttribute.class);
```
That's why it may be better to deffer the task for broader deadline and investigate which marks should we use to choose places for the fix.

Hope I am clear

**Comment by ghchapman** [comment]
Hi @artembilan .  Many thanks for your feedback.  I had already realised I should have run gradle clean, and have pushed a fix for the check style issue.  With that fix, the build succeeds locally.

I agree with you that replacing all AnnotationUtils.findAnnotation calls is not necessarily the way forward, and could have unintended consequences.  It would make sense to defer those until the need arises.

**Comment by artembilan** [comment]
Yeah, I see that you are good with all our tools, configurations, code style etc. :smile: 
Sorry for that extra noise about minor Travis failure.

Re. task... Well, we are busy right now with many other bug fixes in other places and are intended to release the current `4.3.1` enough soon and switch to `5.0` finally. Therefore you feel free to investigate how to determine if we should `AnnotationUtils.findAnnotation` replace or not.

Meanwhile I neither close the PR, nor merge, because it is good one, but isn't finished.

Many thanks for your contribution!

**Comment by ghchapman** [comment]
Is there any scope to merge this change in 4.3.1 as is, and raise a new issue for 5.0.0 for the further analysis step?  The advantage of this would be: 1) the code would be generally available to use sooner and 2) there wouldn't be a long running branch/PR open (I'm never a fan of these as they represent WIP and need maintaining).  I note that the main Spring Project appears to have made these changes piecemeal as well.

**Comment by artembilan** [comment]
Well, we can go any path. The only problem I worry about, if it is really reasonable to merge this minor improvement into the current point release. According our previous private discussion this looks more like academic investigation from your side and don't have any immediate requirement from end-user perspective. (Correct me if I'm wrong). 

On the other hand after some functional analysis of the target `AnnotatedElementUtils.findMergedAnnotation()` premize, we may even decide to reject this `MethodAnnotationPublisherMetadataSource`, but apply some other one.

That's why I'm asking to make some investigation and convince us with some arguments that exactly this should be changed not that one. 

As I said: the PR is fine, but I can't merge it as is with more background. My intention to comeback to it during the proper deadline to have more clean head for better investigation. That's one more "why" I'd prefer do not merge it to current release.

**Comment by garyrussell** [comment]
>long running branch/PR

Our intention is to switch master to 5.0 as soon as 4.3.1 is released so it shouldn't be too long.

**Comment by ghchapman** [comment]
Okay, thanks.  All points taken on board.  I'll go away and do some analysis and justification for my main use case.  Happy to leave this for 5.0 then, I certainly don't want to add to your workload while your busy getting 4.3.1 out.  Many thanks.

**Comment by artembilan** [comment]
No-no. That's fine, @ghchapman !

Sorry, that we are so nit-pick, but that really would be better to avoid unexpected and unwarranted breaking change into the point release. 

But on the other hand we are happy to share some work with contributors even if it can be accepted in the next release. :smile:

**Comment by artembilan** [comment]
I think we good to accept the PR and merge it as is already.

All other `AnnotatedElementUtils` can be addressed on demand.

@garyrussell ?

**Comment by garyrussell** [comment]
Yes; ok with me - @ghchapman thanks for the contribution!

**Comment by artembilan** [comment]
Merged after rebase.

@ghchapman , thank you very much for the contribution and looking forward for more!

**Pull request closed without merging**
