### PR TITLE
Sonar fixes according latest report

### PR DESCRIPTION
**Pull request by artembilan**

### CODE REVIEW

**Comment by artembilan** [comment]
Gary, I think the failure on Travis is related somehow to your latest changes in Spring AMQP we have just recently merged.

Thanks

**Comment by garyrussell** [comment]
Travis

**Comment by artembilan** [comment]
Yeah... I see. That's not yours. Sorry: haven't tested before pushing :shame:

**Review by garyrussell — CHANGES_REQUESTED** [review]

**Comment by garyrussell** [comment]
```
[ant:checkstyle] [ERROR] /home/travis/build/spring-projects/spring-integration/spring-integration-ws/src/main/java/org/springframework/integration/ws/AbstractWebServiceInboundGateway.java:59:24: Reference to instance variable 'headerMapper' needs "this.". [RequireThis]
```

**Pull request merged**
