### PR TITLE
Fixed typo in ip.adoc (Pls cancel this, new PR submitted)

### PR DESCRIPTION
**Pull request by developerworks**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@developerworks Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2623)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2623) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@developerworks Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2623)!

**Comment by developerworks** [comment]
Please cancel this, there is a new PR.

**Comment by artembilan** [comment]
Closed in favor of https://github.com/spring-projects/spring-integration/pull/2624

**Pull request closed without merging**
