### PR TITLE
Fix JavaDoc of JmsInboundGatewaySpec

### PR DESCRIPTION
**Pull request by duydao**
Probably a copy/paste error

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@duydao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3364)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3364) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by duydao** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@duydao This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by artembilan** [comment]
Thanks for contribution; looking forward for more!

**Pull request merged**
