### PR TITLE
Add JavaConfig and DSL Docs (AMQP Inbound)

### PR DESCRIPTION
**Pull request by garyrussell**
@artembilan Over the next few weeks/months, I think we should do a bunch of these (as a back-burner project).

WDYT?

### CODE REVIEW

**Comment by artembilan** [comment]
@garyrussell , for it's fine what you did. And I won't mind to do something similar for everything what will be our best on the allowed time window. But... 
I'd like to hear from other guys (community?) their position on the matter and if they find this style of description as sufficient.
Who can we ask to review?

**Comment by garyrussell** [comment]
I am not sure who we can ask but we get more and more questions about "how do I do this in JavaConfig" so whatever we do will be much  better than what we have now.

There was somebody on the RabbitMQ users group who said he rejected Spring AMQP because (he thought) it was all XML, but when I pointed him to the project he was pleasantly surprised that the stocks example uses JavaConfig throughout.

I think it's important that we give this reasonable priority - i.e. coverage for most elements by the end of 2015.

**Comment by artembilan** [comment]
Regarding the Travis failure: https://jira.spring.io/browse/INT-3840

**Comment by artembilan** [comment]
Well was going to fix this link (http://static.springsource.org/spring-amqp/docs/1.0.x/reference/html/#d0e525) to the 
```
For further information see http://docs.spring.io/spring-amqp/reference/html/_reference.html#_transactions[Transactions with Spring AMQP].
```
And I end up with the error:
```
Execution failed for task ':referenceEpub'.
> javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; systemId: file:///D:/SpringIO/spring-integration/build/reference-work/index.xml; lineNumber: 8962; columnNumber: 36; Attribute name "x" associated with an element type "link" must be foll
owed by the ' = ' character.
```
So, `Epub` doesn't like some symbols in the links, for example `#` or `_`.

I can overcome it from the manual with the top level link and the raw text for the particular chapter.
But from other side we should fix or AMQP Manual, or `asciidoc` plugin to render similar links correctly.
WDYT?

**Comment by garyrussell** [comment]
Pushed outbound and channels - @artembilan when squashing please create a new headline because the base commit headline will be inaccurate.

**Comment by artembilan** [comment]
OK. Pulling your `Outbound` part. and yes, I'll fix the squashed commit message.
But let's revise that link issue first of all!
Thanks

**Comment by artembilan** [comment]
Well, my experiments show me that exactly `asciidoc` plugin doesn't understand the `_` symbol in the links. Looks like it is some special symbol for ASCIIDoc at all.

**Comment by artembilan** [comment]
OK. I see what's going on there:
```
```

**Comment by artembilan** [comment]
OK. I see what's going on there:
```
For further information see
http://docs.spring.io/spring-amqp/reference/html/_reference.html#_transactions[Transactions with Spring AMQP].
_Optional_.
```
Pay attention to the `Optional` word in the `Italic` style. 
The `asciidoc` generate `<emphasis>` for the first `_` and `</emphasis>` for the last one.
See the generated XML:
````xml
For further information see
<link x<link xlink:href="href="http://docs.spring.io/spring-amqp/reference/html/">http://docs.spring.io/spring-amqp/reference/html/</link><emphasis>reference.html#_transactions">Transactions with Spring AMQP</link>.
_Optional</emphasis>.
````
I found how to fix it:
```
http://docs.spring.io/spring-amqp/reference/html/%5Freference.html#%5Ftransactions
```
Pay attention to the ASCII code for the `_`.
So, merging after rebase...

**Comment by artembilan** [comment]
I have : 
```
:referencePdf                 
Font 'Symbol,normal,700' not found. Substituting with 'Symbol,normal,400'.
Font 'ZapfDingbats,normal,700' not found. Substituting with 'ZapfDingbats,normal,400'.
Font 'ZapfDingbats,italic,400' not found. Substituting with 'ZapfDingbats,normal,400'.
Font 'ZapfDingbats,italic,700' not found. Substituting with 'any,italic,700'.
```
even after rebase to the `master` with your neighbour PR.
So, I guess it is something new with this your PR, e.g. 
```
SimpleMessageListenerContainer container = new SimpleMessageListenerContainer(connectionFactory);
```
Is enough long for the PDF view.
Investigating...

**Comment by garyrussell** [comment]
No; these errors are not overflows - they've been there for a while, since we updated to the new plugin; I was not able to find a work-around.

**Comment by artembilan** [comment]
Got it!
So, Merging with last simple polishing after PDF review

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/b2d04bf7deea15a91be29bd37498393a30f549ad

**Pull request closed without merging**
