### PR TITLE
Add Gitpod support

### PR DESCRIPTION
**Pull request by hogah97323**
Add Gitpod support so it will be possible to run the project with Gitpod and easily help with contributions

### CODE REVIEW

**Comment by artembilan** [comment]
I'm not sure why do we need this...
Looks like the preference is a Codespaces instead: https://github.com/spring-projects/spring-petclinic/pull/514#issuecomment-934391253.

Please, elaborate: I don't see that any Spring project does this. So, I'm also reluctant to accept such a change.

**Comment by hogah97323** [comment]
@artembilan seems like Codespaces is not free. Waiting for the response from @dsyer to understand more.

**Comment by dsyer** [comment]
I think the argument for encouraging better contributions is good. Unfortunately I don't think many people will be happy giving Gitpod write access to their repositories (which it needs apparently). Codespaces might be a better option if Microsoft ever make it generally available.

**Comment by hogah97323** [comment]
Ok. I'd like that to be reconsidered in case Microsoft won't open source Codespaces

**Pull request closed without merging**
