### PR TITLE
Addition of Java DSL for SMB module

### PR DESCRIPTION
**Pull request by GregBragg**
As promised here is the addition of the Java DSL package for SMB Support.

### CODE REVIEW

**Comment by GregBragg** [comment]
Looks like the build failed on a different module than SMB, let me know when this is fixed and I'll rebase. Thanks!

**Comment by artembilan** [comment]
> Looks like the build failed on a different module than SMB

On it. Stay tuned.

**Comment by artembilan** [comment]
@GregBragg ,

Fix has been just pushed to `main`.
Please, consider to rebase your branch.
And I'll look into that shortly.

Thanks

PS. I've pushed the Milestone release for tomorrow due to dependency on the planned Spring for GraphQL `1.0.0`, so it might turn that this your new features may make it into that one.

**Comment by GregBragg** [comment]
@artembilan I totally messed up the rebase again... sorry still learning this. I have a merge that needs to be backed out, tried to revert it a couple of times but I'll need to work on this tomorrow to clean it up this branch. I might need to start over unless you have any pointers for this newbie.

Sorry...

**Comment by artembilan** [comment]
Yeah... create an new branch from the latest `main` and cherry-pick exactly your commits.

**Comment by GregBragg** [comment]
Closing this messed up PR in favor of creating a clean branch with the required cherry picked commits from this old branch and will create a new PR for this development effort..

**Pull request closed without merging**
