### PR TITLE
INT-3635: TCP GW: Add remoteTimeoutExpression

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-3635

Add an expression as an alternative to `remote-timeout`.

**needs docs**

### CODE REVIEW

**Comment by artembilan** [comment]
Nothing to complain about.
Are you going to address docs with this PR?
Otherwise I'll merge it as is.

**Comment by garyrussell** [comment]
Yes; I will add docs; I didn't have time last night, but I wanted to give you the opportunity to review.

**Comment by artembilan** [comment]
We wait here for the docs commit

**Comment by garyrussell** [comment]
Pushed; I also started the convention of adding `<!-- MIGRATION -->` where we need a mig. guide update so we can do a check before final release that we have everything covered.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/40c4cb0d417599169af8d143852dd46965f059e4

**Pull request closed without merging**
