### PR TITLE
INT-3742: spring-data-gemfire 1.7 Compatibility

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-3742

Deprecate the message store ctor that takes a `Cache` argument.

### CODE REVIEW

**Comment by artembilan** [comment]
Shouldn't we add 
```
springGemfireVersion = project.hasProperty('springGemfireVersion') ? project.springGemfireVersion : '1.6.0.RELEASE'
```
?
Although, no: IO covers the latest versions for compatibility.
So, merging after local testing against `SD-G-1.7.0.BUILD-SNAPSHOT`

**Comment by garyrussell** [comment]
Right, I tested it with

> ./gradlew :spring-integration-gemfire:springIoCheck -PspringVersion=4.2.0.BUILD-SNAPSHOT --refresh-dependencies --continue  -PplatformVersion=2.0.0.BUILD-SNAPSHOT -PJDK8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/

**Comment by artembilan** [comment]
Merging after rebase...

**Comment by artembilan** [comment]
Merged

**Pull request closed without merging**
