### PR TITLE
INT-3994: DetatchedMimeMessage Transformer

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-3994

Initial commit for review.

### CODE REVIEW

**Comment by artembilan** [comment]
Gary, I'm an ignoramus in mail API therefore I don't understand (and from here don't like :smile: ) this solution.
From the general *Integration* perspective, when we are going to travel over the network (like it is with SCSt binders), I'd say that it would be better do not transfer mail-specific objects like `MimeMessage` and `Folder` at all, independently of the serialization system.

Having that I'd introduce some more general `transformer` which allows to configure `headers-to-map` (defaults to `*`) and extracts the `MimeMessage` 's content on the matter, maybe just to the `byte[]` directly...
Although the `header-mappig` logic would be better in the `AbstractMailReceiver` to be consistence with many other `inbound-channel-adapter` s.
WDYT?

**Comment by garyrussell** [comment]
The problem is there is all kinds of complicated handling of different message body types - I didn't want to get involved with all that. My original implementation didn't subclass MimeMessage, it just implemented Part and MimePart - this was just an attempt to allow downstream apps to still interpret it as a MimeMessage, but I'm happy to revisit and transform to some simple POJO instead.

**Comment by artembilan** [comment]
Pay attention to my [comment](https://github.com/spring-cloud/spring-cloud-stream-modules/pull/255#issuecomment-212054524), BTW.
I would like to hear from you back what is your plans here.

Thank you!

**Comment by garyrussell** [comment]
I will rework - but I was asked to help with some work on SCSt - will pick this up later this week.

**Comment by garyrussell** [comment]
Closed in favor of #1778

**Pull request closed without merging**
