### PR TITLE
INT-4362: MMIH Catch Conversion Exception

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-4362

INT-4312 added a JSON conversion when there is a single method with a non-String parameter.

Add more tests for parameters of type `Message`.

Catch conversion exceptions and use the message as-is if the conversion fails.

### CODE REVIEW

**Comment by artembilan** [comment]
I know that isn't related to your changes, but still would be great to have your double check for the Travis failure report:
```
org.springframework.integration.ip.tcp.TcpConfigOutboundGatewayTests > testOutboundInsideChain FAILED

    org.springframework.messaging.MessagingException at TcpConfigOutboundGatewayTests.java:180

        Caused by: org.springframework.messaging.MessagingException at TcpConfigOutboundGatewayTests.java:180

            Caused by: java.net.ConnectException at TcpConfigOutboundGatewayTests.java:180
```
Thanks

**Comment by garyrussell** [comment]
That requires a large change and should not be attached to this PR. [INT-4364 | https://jira.spring.io/browse/INT-4364].

**Review by artembilan — APPROVED** [review]
LGTM

Will be merged when our CI comes back to life.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration/commit/70c166fbfdeafafa08a9445f191480ec4a75997d after rebase and resolving conflicts in the `MethodInvokingMessageProcessorTests`

**Pull request closed without merging**
