### PR TITLE
GH-8659: Fix the WatchServiceDirectoryScanner to detect new file afte…

### PR DESCRIPTION
**Pull request by pziobron**
Fix the WatchServiceDirectoryScanner to detect new file after renaming the sub-folder of the watched folder (Java 7 WatchService)

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
All looks good, however I would like to suggest some change to the `file.adoc`.
Go to the `[[watch-service-directory-scanner]]` section and explain there in the end that we need to track also `WatchEventType.MODIFY` and `WatchEventType.DELETE` event types if sub-directories can be renamed.

**Review by artembilan — CHANGES_REQUESTED** [review]
The test has failed, probably due to your change: 
```
WatchServiceDirectoryScannerTests > testWatchServiceDirectoryScanner() FAILED
    java.lang.AssertionError at WatchServiceDirectoryScannerTests.java:220
```

Please, revise.

**Comment by pziobron** [comment]
The fix seems to solve the problem on Windows - the files are detected properly in the sub-folder (of the watched folder) after renaming it.
I've tried to write a test for this scenario but it is hard to emulate it in Java (creating empty folder in File Explorer and renaming it). I am not sure if that's even possible.
I will experiment with that a bit :)

**Comment by pziobron** [comment]
I've tried to replicate the issue in Java in order to write the Integration test which covers that issue.
Unfortunately, I haven't managed to do that.
I've been using: 

1. File.mkdir()
2. File.renameTo(...)/Files.move(...)
3. File.createTempFile(...)

with no success - the file in sub-directory is detected properly.

The issue can be replicated in Windows with the File Explorer or with the Command Line by using the following commands:

1. md test1
2. move test1 test2
3. copy someFile test2

Theoretically, the Runtime.getRuntime().exec(...) could be used for the integration test but it would work obviously only for Windows (or for all Os'es when mapping md -> mkdir, copy -> cp etc....).
Nevertheless, I am not sure if that is a good idea (this could be tricky) ?

I've updated the documentation as You requested.

**Review by artembilan — CHANGES_REQUESTED** [review]

**Comment by artembilan** [comment]
... and cherry-picked to `6.1.x`, `6.0.x` & `5.5.x`.

@pziobron ,

thank you for contribution; looking forward for more!

**Pull request merged**
